// Code generated by protoc-gen-go.
// source: arena.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 竞技场排行
type Arena_Rank_Info_ struct {
	UserID           *int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	RankNo           *int32  `protobuf:"varint,2,opt,name=RankNo" json:"RankNo,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Score            *int32  `protobuf:"varint,4,opt,name=Score" json:"Score,omitempty"`
	Country          *int32  `protobuf:"varint,5,opt,name=Country" json:"Country,omitempty"`
	MaxChapter       *int32  `protobuf:"varint,6,opt,name=MaxChapter" json:"MaxChapter,omitempty"`
	Formation        []int32 `protobuf:"varint,7,rep,name=Formation" json:"Formation,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Arena_Rank_Info_) Reset()                    { *m = Arena_Rank_Info_{} }
func (m *Arena_Rank_Info_) String() string            { return proto.CompactTextString(m) }
func (*Arena_Rank_Info_) ProtoMessage()               {}
func (*Arena_Rank_Info_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Arena_Rank_Info_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Arena_Rank_Info_) GetRankNo() int32 {
	if m != nil && m.RankNo != nil {
		return *m.RankNo
	}
	return 0
}

func (m *Arena_Rank_Info_) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Arena_Rank_Info_) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Arena_Rank_Info_) GetCountry() int32 {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return 0
}

func (m *Arena_Rank_Info_) GetMaxChapter() int32 {
	if m != nil && m.MaxChapter != nil {
		return *m.MaxChapter
	}
	return 0
}

func (m *Arena_Rank_Info_) GetFormation() []int32 {
	if m != nil {
		return m.Formation
	}
	return nil
}

type Arena_Monster_Info_ struct {
	FamilyID         *int32  `protobuf:"varint,1,opt,name=FamilyID" json:"FamilyID,omitempty"`
	SkillLv          []int32 `protobuf:"varint,2,rep,name=SkillLv" json:"SkillLv,omitempty"`
	TalentLv         []int32 `protobuf:"varint,3,rep,name=TalentLv" json:"TalentLv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Arena_Monster_Info_) Reset()                    { *m = Arena_Monster_Info_{} }
func (m *Arena_Monster_Info_) String() string            { return proto.CompactTextString(m) }
func (*Arena_Monster_Info_) ProtoMessage()               {}
func (*Arena_Monster_Info_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Arena_Monster_Info_) GetFamilyID() int32 {
	if m != nil && m.FamilyID != nil {
		return *m.FamilyID
	}
	return 0
}

func (m *Arena_Monster_Info_) GetSkillLv() []int32 {
	if m != nil {
		return m.SkillLv
	}
	return nil
}

func (m *Arena_Monster_Info_) GetTalentLv() []int32 {
	if m != nil {
		return m.TalentLv
	}
	return nil
}

type Arena_Battle_MonsterInfo_ struct {
	ID               *int32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Lv               *int32  `protobuf:"varint,2,opt,name=Lv" json:"Lv,omitempty"`
	Hp               *int32  `protobuf:"varint,3,opt,name=Hp" json:"Hp,omitempty"`
	Pos              *int32  `protobuf:"varint,4,opt,name=Pos" json:"Pos,omitempty"`
	SkillLv          []int32 `protobuf:"varint,5,rep,name=SkillLv" json:"SkillLv,omitempty"`
	TalentLv         []int32 `protobuf:"varint,6,rep,name=TalentLv" json:"TalentLv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Arena_Battle_MonsterInfo_) Reset()                    { *m = Arena_Battle_MonsterInfo_{} }
func (m *Arena_Battle_MonsterInfo_) String() string            { return proto.CompactTextString(m) }
func (*Arena_Battle_MonsterInfo_) ProtoMessage()               {}
func (*Arena_Battle_MonsterInfo_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Arena_Battle_MonsterInfo_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Arena_Battle_MonsterInfo_) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *Arena_Battle_MonsterInfo_) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Arena_Battle_MonsterInfo_) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *Arena_Battle_MonsterInfo_) GetSkillLv() []int32 {
	if m != nil {
		return m.SkillLv
	}
	return nil
}

func (m *Arena_Battle_MonsterInfo_) GetTalentLv() []int32 {
	if m != nil {
		return m.TalentLv
	}
	return nil
}

type Arena_Player_Info struct {
	Uid              *int64                 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Score            *int32                 `protobuf:"varint,3,opt,name=Score" json:"Score,omitempty"`
	Div              *int32                 `protobuf:"varint,4,opt,name=Div" json:"Div,omitempty"`
	Role             *Role_Info_            `protobuf:"bytes,5,opt,name=Role" json:"Role,omitempty"`
	Formation        []*Arena_Monster_Info_ `protobuf:"bytes,6,rep,name=Formation" json:"Formation,omitempty"`
	Country          *int32                 `protobuf:"varint,7,opt,name=Country" json:"Country,omitempty"`
	Streak           *int32                 `protobuf:"varint,8,opt,name=Streak" json:"Streak,omitempty"`
	IconID           *int32                 `protobuf:"varint,9,opt,name=IconID" json:"IconID,omitempty"`
	IconUrl          *string                `protobuf:"bytes,10,opt,name=IconUrl" json:"IconUrl,omitempty"`
	Gold             *int32                 `protobuf:"varint,11,opt,name=Gold" json:"Gold,omitempty"`
	MaxChapter       *int32                 `protobuf:"varint,12,opt,name=MaxChapter" json:"MaxChapter,omitempty"`
	RegTime          *int64                 `protobuf:"varint,13,opt,name=RegTime" json:"RegTime,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Arena_Player_Info) Reset()                    { *m = Arena_Player_Info{} }
func (m *Arena_Player_Info) String() string            { return proto.CompactTextString(m) }
func (*Arena_Player_Info) ProtoMessage()               {}
func (*Arena_Player_Info) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Arena_Player_Info) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Arena_Player_Info) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Arena_Player_Info) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Arena_Player_Info) GetDiv() int32 {
	if m != nil && m.Div != nil {
		return *m.Div
	}
	return 0
}

func (m *Arena_Player_Info) GetRole() *Role_Info_ {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Arena_Player_Info) GetFormation() []*Arena_Monster_Info_ {
	if m != nil {
		return m.Formation
	}
	return nil
}

func (m *Arena_Player_Info) GetCountry() int32 {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return 0
}

func (m *Arena_Player_Info) GetStreak() int32 {
	if m != nil && m.Streak != nil {
		return *m.Streak
	}
	return 0
}

func (m *Arena_Player_Info) GetIconID() int32 {
	if m != nil && m.IconID != nil {
		return *m.IconID
	}
	return 0
}

func (m *Arena_Player_Info) GetIconUrl() string {
	if m != nil && m.IconUrl != nil {
		return *m.IconUrl
	}
	return ""
}

func (m *Arena_Player_Info) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Arena_Player_Info) GetMaxChapter() int32 {
	if m != nil && m.MaxChapter != nil {
		return *m.MaxChapter
	}
	return 0
}

func (m *Arena_Player_Info) GetRegTime() int64 {
	if m != nil && m.RegTime != nil {
		return *m.RegTime
	}
	return 0
}

// 请求 排行榜
type Req_Arena_Rank_ struct {
	UserID           *int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	BeginRank        *int32  `protobuf:"varint,2,opt,name=BeginRank" json:"BeginRank,omitempty"`
	Type             *int32  `protobuf:"varint,3,opt,name=Type" json:"Type,omitempty"`
	FriendIDs        []int64 `protobuf:"varint,4,rep,name=FriendIDs" json:"FriendIDs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Arena_Rank_) Reset()                    { *m = Req_Arena_Rank_{} }
func (m *Req_Arena_Rank_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Rank_) ProtoMessage()               {}
func (*Req_Arena_Rank_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Req_Arena_Rank_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Arena_Rank_) GetBeginRank() int32 {
	if m != nil && m.BeginRank != nil {
		return *m.BeginRank
	}
	return 0
}

func (m *Req_Arena_Rank_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Req_Arena_Rank_) GetFriendIDs() []int64 {
	if m != nil {
		return m.FriendIDs
	}
	return nil
}

// 响应 排行榜
type Resp_Arena_Rank_ struct {
	UserID           *int64              `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Rank             []*Arena_Rank_Info_ `protobuf:"bytes,2,rep,name=Rank" json:"Rank,omitempty"`
	Type             *int32              `protobuf:"varint,3,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Resp_Arena_Rank_) Reset()                    { *m = Resp_Arena_Rank_{} }
func (m *Resp_Arena_Rank_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Rank_) ProtoMessage()               {}
func (*Resp_Arena_Rank_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Resp_Arena_Rank_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Arena_Rank_) GetRank() []*Arena_Rank_Info_ {
	if m != nil {
		return m.Rank
	}
	return nil
}

func (m *Resp_Arena_Rank_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type Req_Arena_OpenTime_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_OpenTime_) Reset()                    { *m = Req_Arena_OpenTime_{} }
func (m *Req_Arena_OpenTime_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_OpenTime_) ProtoMessage()               {}
func (*Req_Arena_OpenTime_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type Resp_Arena_OpenTime_ struct {
	OpenTime         *int64 `protobuf:"varint,1,opt,name=OpenTime" json:"OpenTime,omitempty"`
	CloseTime        *int64 `protobuf:"varint,2,opt,name=CloseTime" json:"CloseTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Arena_OpenTime_) Reset()                    { *m = Resp_Arena_OpenTime_{} }
func (m *Resp_Arena_OpenTime_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_OpenTime_) ProtoMessage()               {}
func (*Resp_Arena_OpenTime_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Resp_Arena_OpenTime_) GetOpenTime() int64 {
	if m != nil && m.OpenTime != nil {
		return *m.OpenTime
	}
	return 0
}

func (m *Resp_Arena_OpenTime_) GetCloseTime() int64 {
	if m != nil && m.CloseTime != nil {
		return *m.CloseTime
	}
	return 0
}

// 请求竞技场信息
type Req_Arena_Info_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_Info_) Reset()                    { *m = Req_Arena_Info_{} }
func (m *Req_Arena_Info_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Info_) ProtoMessage()               {}
func (*Req_Arena_Info_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *Req_Arena_Info_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 响应竞技场信息
type Resp_Arena_Info_ struct {
	ArenaScore       *int32           `protobuf:"varint,1,opt,name=ArenaScore" json:"ArenaScore,omitempty"`
	EndTime          *int64           `protobuf:"varint,2,opt,name=EndTime" json:"EndTime,omitempty"`
	ArenaRewards     []*Arena_Reward_ `protobuf:"bytes,3,rep,name=ArenaRewards" json:"ArenaRewards,omitempty"`
	UserID           *int64           `protobuf:"varint,4,opt,name=UserID" json:"UserID,omitempty"`
	SeasonID         *int32           `protobuf:"varint,5,opt,name=SeasonID" json:"SeasonID,omitempty"`
	Rank             *int32           `protobuf:"varint,6,opt,name=Rank" json:"Rank,omitempty"`
	GameNum          *int32           `protobuf:"varint,7,opt,name=GameNum" json:"GameNum,omitempty"`
	GameWin          *int32           `protobuf:"varint,8,opt,name=GameWin" json:"GameWin,omitempty"`
	ChestIcon        *int32           `protobuf:"varint,9,opt,name=ChestIcon" json:"ChestIcon,omitempty"`
	ChestRewards     []*Reward_Info_  `protobuf:"bytes,10,rep,name=ChestRewards" json:"ChestRewards,omitempty"`
	Rewards          []*Reward_Info_  `protobuf:"bytes,11,rep,name=Rewards" json:"Rewards,omitempty"`
	OpenTime         *int64           `protobuf:"varint,12,opt,name=OpenTime" json:"OpenTime,omitempty"`
	CloseTime        *int64           `protobuf:"varint,13,opt,name=CloseTime" json:"CloseTime,omitempty"`
	Honor            *int32           `protobuf:"varint,14,opt,name=Honor" json:"Honor,omitempty"`
	DailyHonor       *int32           `protobuf:"varint,15,opt,name=DailyHonor" json:"DailyHonor,omitempty"`
	DailyHonorMax    *int32           `protobuf:"varint,16,opt,name=DailyHonorMax" json:"DailyHonorMax,omitempty"`
	NextRefreshTime  *int64           `protobuf:"varint,17,opt,name=NextRefreshTime" json:"NextRefreshTime,omitempty"`
	BoxIcon          *int32           `protobuf:"varint,18,opt,name=BoxIcon" json:"BoxIcon,omitempty"`
	MaxStar          *int32           `protobuf:"varint,19,opt,name=MaxStar" json:"MaxStar,omitempty"`
	Star             *int32           `protobuf:"varint,20,opt,name=Star" json:"Star,omitempty"`
	OldScore         *int32           `protobuf:"varint,21,opt,name=OldScore" json:"OldScore,omitempty"`
	Vit              *int32           `protobuf:"varint,22,opt,name=Vit" json:"Vit,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Resp_Arena_Info_) Reset()                    { *m = Resp_Arena_Info_{} }
func (m *Resp_Arena_Info_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Info_) ProtoMessage()               {}
func (*Resp_Arena_Info_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Resp_Arena_Info_) GetArenaScore() int32 {
	if m != nil && m.ArenaScore != nil {
		return *m.ArenaScore
	}
	return 0
}

func (m *Resp_Arena_Info_) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *Resp_Arena_Info_) GetArenaRewards() []*Arena_Reward_ {
	if m != nil {
		return m.ArenaRewards
	}
	return nil
}

func (m *Resp_Arena_Info_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Arena_Info_) GetSeasonID() int32 {
	if m != nil && m.SeasonID != nil {
		return *m.SeasonID
	}
	return 0
}

func (m *Resp_Arena_Info_) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *Resp_Arena_Info_) GetGameNum() int32 {
	if m != nil && m.GameNum != nil {
		return *m.GameNum
	}
	return 0
}

func (m *Resp_Arena_Info_) GetGameWin() int32 {
	if m != nil && m.GameWin != nil {
		return *m.GameWin
	}
	return 0
}

func (m *Resp_Arena_Info_) GetChestIcon() int32 {
	if m != nil && m.ChestIcon != nil {
		return *m.ChestIcon
	}
	return 0
}

func (m *Resp_Arena_Info_) GetChestRewards() []*Reward_Info_ {
	if m != nil {
		return m.ChestRewards
	}
	return nil
}

func (m *Resp_Arena_Info_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Resp_Arena_Info_) GetOpenTime() int64 {
	if m != nil && m.OpenTime != nil {
		return *m.OpenTime
	}
	return 0
}

func (m *Resp_Arena_Info_) GetCloseTime() int64 {
	if m != nil && m.CloseTime != nil {
		return *m.CloseTime
	}
	return 0
}

func (m *Resp_Arena_Info_) GetHonor() int32 {
	if m != nil && m.Honor != nil {
		return *m.Honor
	}
	return 0
}

func (m *Resp_Arena_Info_) GetDailyHonor() int32 {
	if m != nil && m.DailyHonor != nil {
		return *m.DailyHonor
	}
	return 0
}

func (m *Resp_Arena_Info_) GetDailyHonorMax() int32 {
	if m != nil && m.DailyHonorMax != nil {
		return *m.DailyHonorMax
	}
	return 0
}

func (m *Resp_Arena_Info_) GetNextRefreshTime() int64 {
	if m != nil && m.NextRefreshTime != nil {
		return *m.NextRefreshTime
	}
	return 0
}

func (m *Resp_Arena_Info_) GetBoxIcon() int32 {
	if m != nil && m.BoxIcon != nil {
		return *m.BoxIcon
	}
	return 0
}

func (m *Resp_Arena_Info_) GetMaxStar() int32 {
	if m != nil && m.MaxStar != nil {
		return *m.MaxStar
	}
	return 0
}

func (m *Resp_Arena_Info_) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *Resp_Arena_Info_) GetOldScore() int32 {
	if m != nil && m.OldScore != nil {
		return *m.OldScore
	}
	return 0
}

func (m *Resp_Arena_Info_) GetVit() int32 {
	if m != nil && m.Vit != nil {
		return *m.Vit
	}
	return 0
}

// 请求 竞技场荣耀商店
type Req_Honor_Shop_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	LastScore        *int32 `protobuf:"varint,2,opt,name=LastScore" json:"LastScore,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Honor_Shop_) Reset()                    { *m = Req_Honor_Shop_{} }
func (m *Req_Honor_Shop_) String() string            { return proto.CompactTextString(m) }
func (*Req_Honor_Shop_) ProtoMessage()               {}
func (*Req_Honor_Shop_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *Req_Honor_Shop_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Honor_Shop_) GetLastScore() int32 {
	if m != nil && m.LastScore != nil {
		return *m.LastScore
	}
	return 0
}

// 响应 荣耀商店
type Resp_Honor_Shop_ struct {
	UserID           *int64          `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Items            []*Reward_Info_ `protobuf:"bytes,2,rep,name=Items" json:"Items,omitempty"`
	Price            []int32         `protobuf:"varint,3,rep,name=Price" json:"Price,omitempty"`
	BuyTimes         []int32         `protobuf:"varint,4,rep,name=BuyTimes" json:"BuyTimes,omitempty"`
	Limit            []int32         `protobuf:"varint,5,rep,name=Limit" json:"Limit,omitempty"`
	ItemID           []int32         `protobuf:"varint,6,rep,name=ItemID" json:"ItemID,omitempty"`
	NextRefreshTime  *int64          `protobuf:"varint,7,opt,name=NextRefreshTime" json:"NextRefreshTime,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Honor_Shop_) Reset()                    { *m = Resp_Honor_Shop_{} }
func (m *Resp_Honor_Shop_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Honor_Shop_) ProtoMessage()               {}
func (*Resp_Honor_Shop_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *Resp_Honor_Shop_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Honor_Shop_) GetItems() []*Reward_Info_ {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Resp_Honor_Shop_) GetPrice() []int32 {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Resp_Honor_Shop_) GetBuyTimes() []int32 {
	if m != nil {
		return m.BuyTimes
	}
	return nil
}

func (m *Resp_Honor_Shop_) GetLimit() []int32 {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *Resp_Honor_Shop_) GetItemID() []int32 {
	if m != nil {
		return m.ItemID
	}
	return nil
}

func (m *Resp_Honor_Shop_) GetNextRefreshTime() int64 {
	if m != nil && m.NextRefreshTime != nil {
		return *m.NextRefreshTime
	}
	return 0
}

// 请求 荣耀商店购买
type Req_Honor_Buy_ struct {
	ItemID           *int32 `protobuf:"varint,1,opt,name=ItemID" json:"ItemID,omitempty"`
	ItemType         *int32 `protobuf:"varint,2,opt,name=ItemType" json:"ItemType,omitempty"`
	BaseID           *int32 `protobuf:"varint,3,opt,name=BaseID" json:"BaseID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Honor_Buy_) Reset()                    { *m = Req_Honor_Buy_{} }
func (m *Req_Honor_Buy_) String() string            { return proto.CompactTextString(m) }
func (*Req_Honor_Buy_) ProtoMessage()               {}
func (*Req_Honor_Buy_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *Req_Honor_Buy_) GetItemID() int32 {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return 0
}

func (m *Req_Honor_Buy_) GetItemType() int32 {
	if m != nil && m.ItemType != nil {
		return *m.ItemType
	}
	return 0
}

func (m *Req_Honor_Buy_) GetBaseID() int32 {
	if m != nil && m.BaseID != nil {
		return *m.BaseID
	}
	return 0
}

// 响应 荣耀商店购买
type Resp_Honor_Buy_ struct {
	Rewards          []*Reward_Info_ `protobuf:"bytes,1,rep,name=Rewards" json:"Rewards,omitempty"`
	BuyTimes         *int32          `protobuf:"varint,2,opt,name=BuyTimes" json:"BuyTimes,omitempty"`
	ItemID           *int32          `protobuf:"varint,3,opt,name=ItemID" json:"ItemID,omitempty"`
	Honor            *int32          `protobuf:"varint,4,opt,name=Honor" json:"Honor,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Honor_Buy_) Reset()                    { *m = Resp_Honor_Buy_{} }
func (m *Resp_Honor_Buy_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Honor_Buy_) ProtoMessage()               {}
func (*Resp_Honor_Buy_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *Resp_Honor_Buy_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Resp_Honor_Buy_) GetBuyTimes() int32 {
	if m != nil && m.BuyTimes != nil {
		return *m.BuyTimes
	}
	return 0
}

func (m *Resp_Honor_Buy_) GetItemID() int32 {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return 0
}

func (m *Resp_Honor_Buy_) GetHonor() int32 {
	if m != nil && m.Honor != nil {
		return *m.Honor
	}
	return 0
}

// 竞技场奖励
type Arena_Reward_ struct {
	Score            *int32          `protobuf:"varint,1,opt,name=Score" json:"Score,omitempty"`
	DivName          *int32          `protobuf:"varint,2,opt,name=DivName" json:"DivName,omitempty"`
	DicIcon          *string         `protobuf:"bytes,3,opt,name=DicIcon" json:"DicIcon,omitempty"`
	Rewards          []*Reward_Info_ `protobuf:"bytes,4,rep,name=Rewards" json:"Rewards,omitempty"`
	Segment          *int32          `protobuf:"varint,5,opt,name=Segment" json:"Segment,omitempty"`
	StarNum          *int32          `protobuf:"varint,6,opt,name=StarNum" json:"StarNum,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Arena_Reward_) Reset()                    { *m = Arena_Reward_{} }
func (m *Arena_Reward_) String() string            { return proto.CompactTextString(m) }
func (*Arena_Reward_) ProtoMessage()               {}
func (*Arena_Reward_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *Arena_Reward_) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Arena_Reward_) GetDivName() int32 {
	if m != nil && m.DivName != nil {
		return *m.DivName
	}
	return 0
}

func (m *Arena_Reward_) GetDicIcon() string {
	if m != nil && m.DicIcon != nil {
		return *m.DicIcon
	}
	return ""
}

func (m *Arena_Reward_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Arena_Reward_) GetSegment() int32 {
	if m != nil && m.Segment != nil {
		return *m.Segment
	}
	return 0
}

func (m *Arena_Reward_) GetStarNum() int32 {
	if m != nil && m.StarNum != nil {
		return *m.StarNum
	}
	return 0
}

// 请求竞技场匹配
type Req_Arena_Match_ struct {
	OpType           *int32             `protobuf:"varint,1,opt,name=OpType" json:"OpType,omitempty"`
	UserID           *int64             `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	PlayerInfo       *Arena_Player_Info `protobuf:"bytes,3,opt,name=PlayerInfo" json:"PlayerInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Req_Arena_Match_) Reset()                    { *m = Req_Arena_Match_{} }
func (m *Req_Arena_Match_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Match_) ProtoMessage()               {}
func (*Req_Arena_Match_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *Req_Arena_Match_) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *Req_Arena_Match_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Arena_Match_) GetPlayerInfo() *Arena_Player_Info {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// 响应竞技场匹配( 只有两边都匹配成功的时候才会 下发 )
type Resp_Arena_Match_ struct {
	RoomID           *int32             `protobuf:"varint,1,opt,name=RoomID" json:"RoomID,omitempty"`
	RoundNum         *int32             `protobuf:"varint,2,opt,name=RoundNum" json:"RoundNum,omitempty"`
	PlayerRed        *Arena_Player_Info `protobuf:"bytes,3,opt,name=PlayerRed" json:"PlayerRed,omitempty"`
	PlayerBlud       *Arena_Player_Info `protobuf:"bytes,4,opt,name=PlayerBlud" json:"PlayerBlud,omitempty"`
	HeroIDs          []int32            `protobuf:"varint,5,rep,name=HeroIDs" json:"HeroIDs,omitempty"`
	UserID           *int64             `protobuf:"varint,6,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Resp_Arena_Match_) Reset()                    { *m = Resp_Arena_Match_{} }
func (m *Resp_Arena_Match_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Match_) ProtoMessage()               {}
func (*Resp_Arena_Match_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *Resp_Arena_Match_) GetRoomID() int32 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

func (m *Resp_Arena_Match_) GetRoundNum() int32 {
	if m != nil && m.RoundNum != nil {
		return *m.RoundNum
	}
	return 0
}

func (m *Resp_Arena_Match_) GetPlayerRed() *Arena_Player_Info {
	if m != nil {
		return m.PlayerRed
	}
	return nil
}

func (m *Resp_Arena_Match_) GetPlayerBlud() *Arena_Player_Info {
	if m != nil {
		return m.PlayerBlud
	}
	return nil
}

func (m *Resp_Arena_Match_) GetHeroIDs() []int32 {
	if m != nil {
		return m.HeroIDs
	}
	return nil
}

func (m *Resp_Arena_Match_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 请求战斗开始( 加载进度条 结束以后发送 )
type Req_Arena_Start_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_Start_) Reset()                    { *m = Req_Arena_Start_{} }
func (m *Req_Arena_Start_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Start_) ProtoMessage()               {}
func (*Req_Arena_Start_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *Req_Arena_Start_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 响应战斗开始
type Resp_Arena_Start_ struct {
	Step             *int32      `protobuf:"varint,1,opt,name=Step" json:"Step,omitempty"`
	EndTime          *int64      `protobuf:"varint,2,opt,name=EndTime" json:"EndTime,omitempty"`
	TableInfo        *TableInfo_ `protobuf:"bytes,3,opt,name=TableInfo" json:"TableInfo,omitempty"`
	UserID           *int64      `protobuf:"varint,4,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Resp_Arena_Start_) Reset()                    { *m = Resp_Arena_Start_{} }
func (m *Resp_Arena_Start_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Start_) ProtoMessage()               {}
func (*Resp_Arena_Start_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *Resp_Arena_Start_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Resp_Arena_Start_) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *Resp_Arena_Start_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *Resp_Arena_Start_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 请求 战斗中消除（生成怪）
type Req_Arena_GenMonster_ struct {
	UserID           *int64                       `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Step             *int32                       `protobuf:"varint,2,opt,name=Step" json:"Step,omitempty"`
	HeroInfos        []*Arena_Battle_MonsterInfo_ `protobuf:"bytes,3,rep,name=HeroInfos" json:"HeroInfos,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *Req_Arena_GenMonster_) Reset()                    { *m = Req_Arena_GenMonster_{} }
func (m *Req_Arena_GenMonster_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_GenMonster_) ProtoMessage()               {}
func (*Req_Arena_GenMonster_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *Req_Arena_GenMonster_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Arena_GenMonster_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Req_Arena_GenMonster_) GetHeroInfos() []*Arena_Battle_MonsterInfo_ {
	if m != nil {
		return m.HeroInfos
	}
	return nil
}

// 转发 战斗中消除(真人玩家使用)
type Resp_Arena_GenMonster_ struct {
	UserID           *int64                       `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Step             *int32                       `protobuf:"varint,2,opt,name=Step" json:"Step,omitempty"`
	HeroInfos        []*Arena_Battle_MonsterInfo_ `protobuf:"bytes,3,rep,name=HeroInfos" json:"HeroInfos,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *Resp_Arena_GenMonster_) Reset()                    { *m = Resp_Arena_GenMonster_{} }
func (m *Resp_Arena_GenMonster_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_GenMonster_) ProtoMessage()               {}
func (*Resp_Arena_GenMonster_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *Resp_Arena_GenMonster_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Arena_GenMonster_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Resp_Arena_GenMonster_) GetHeroInfos() []*Arena_Battle_MonsterInfo_ {
	if m != nil {
		return m.HeroInfos
	}
	return nil
}

// 转发 战斗中消除(机器人使用)
type Fw_Arena_GenMonster_ struct {
	UserID           *int64             `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Step             *int32             `protobuf:"varint,2,opt,name=Step" json:"Step,omitempty"`
	HeroInfos        []*BattleHeroInfo_ `protobuf:"bytes,3,rep,name=HeroInfos" json:"HeroInfos,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Fw_Arena_GenMonster_) Reset()                    { *m = Fw_Arena_GenMonster_{} }
func (m *Fw_Arena_GenMonster_) String() string            { return proto.CompactTextString(m) }
func (*Fw_Arena_GenMonster_) ProtoMessage()               {}
func (*Fw_Arena_GenMonster_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *Fw_Arena_GenMonster_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Fw_Arena_GenMonster_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Fw_Arena_GenMonster_) GetHeroInfos() []*BattleHeroInfo_ {
	if m != nil {
		return m.HeroInfos
	}
	return nil
}

// 请求回合结束（消除结束，准备开始战斗）
type Req_Arena_Round_ struct {
	TableInfo        *TableInfo_                  `protobuf:"bytes,1,opt,name=TableInfo" json:"TableInfo,omitempty"`
	HeroInfos        []*Arena_Battle_MonsterInfo_ `protobuf:"bytes,2,rep,name=HeroInfos" json:"HeroInfos,omitempty"`
	UserID           *int64                       `protobuf:"varint,3,opt,name=UserID" json:"UserID,omitempty"`
	Power            *int32                       `protobuf:"varint,4,opt,name=Power" json:"Power,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *Req_Arena_Round_) Reset()                    { *m = Req_Arena_Round_{} }
func (m *Req_Arena_Round_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Round_) ProtoMessage()               {}
func (*Req_Arena_Round_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *Req_Arena_Round_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *Req_Arena_Round_) GetHeroInfos() []*Arena_Battle_MonsterInfo_ {
	if m != nil {
		return m.HeroInfos
	}
	return nil
}

func (m *Req_Arena_Round_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Arena_Round_) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

// 响应回合结束( 只有两边都结束， 或者倒计时结束才会下发 )
type Resp_Arena_Round_ struct {
	Victor           *int64                       `protobuf:"varint,1,opt,name=Victor" json:"Victor,omitempty"`
	HeroRed          []*Arena_Battle_MonsterInfo_ `protobuf:"bytes,2,rep,name=HeroRed" json:"HeroRed,omitempty"`
	HeroBlud         []*Arena_Battle_MonsterInfo_ `protobuf:"bytes,3,rep,name=HeroBlud" json:"HeroBlud,omitempty"`
	RandSed          *int64                       `protobuf:"varint,4,opt,name=RandSed" json:"RandSed,omitempty"`
	UserID           *int64                       `protobuf:"varint,5,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *Resp_Arena_Round_) Reset()                    { *m = Resp_Arena_Round_{} }
func (m *Resp_Arena_Round_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Round_) ProtoMessage()               {}
func (*Resp_Arena_Round_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *Resp_Arena_Round_) GetVictor() int64 {
	if m != nil && m.Victor != nil {
		return *m.Victor
	}
	return 0
}

func (m *Resp_Arena_Round_) GetHeroRed() []*Arena_Battle_MonsterInfo_ {
	if m != nil {
		return m.HeroRed
	}
	return nil
}

func (m *Resp_Arena_Round_) GetHeroBlud() []*Arena_Battle_MonsterInfo_ {
	if m != nil {
		return m.HeroBlud
	}
	return nil
}

func (m *Resp_Arena_Round_) GetRandSed() int64 {
	if m != nil && m.RandSed != nil {
		return *m.RandSed
	}
	return 0
}

func (m *Resp_Arena_Round_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 请求 战斗结束（客户端表现结束）
type Req_Arena_Round_End_ struct {
	// 先由客户端计算战斗结果，并上报
	Ret              *int32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	UserID           *int64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_Round_End_) Reset()                    { *m = Req_Arena_Round_End_{} }
func (m *Req_Arena_Round_End_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Round_End_) ProtoMessage()               {}
func (*Req_Arena_Round_End_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *Req_Arena_Round_End_) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *Req_Arena_Round_End_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 响应 战斗结束（客户端表现结束）
type Resp_Arena_Round_End_ struct {
	Step             *int32 `protobuf:"varint,1,opt,name=Step" json:"Step,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=EndTime" json:"EndTime,omitempty"`
	UserID           *int64 `protobuf:"varint,3,opt,name=UserID" json:"UserID,omitempty"`
	RoundVictorUid   *int64 `protobuf:"varint,4,opt,name=RoundVictorUid" json:"RoundVictorUid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Arena_Round_End_) Reset()                    { *m = Resp_Arena_Round_End_{} }
func (m *Resp_Arena_Round_End_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Round_End_) ProtoMessage()               {}
func (*Resp_Arena_Round_End_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *Resp_Arena_Round_End_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Resp_Arena_Round_End_) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *Resp_Arena_Round_End_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Arena_Round_End_) GetRoundVictorUid() int64 {
	if m != nil && m.RoundVictorUid != nil {
		return *m.RoundVictorUid
	}
	return 0
}

type Req_Arena_Exit_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_Exit_) Reset()                    { *m = Req_Arena_Exit_{} }
func (m *Req_Arena_Exit_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Exit_) ProtoMessage()               {}
func (*Req_Arena_Exit_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *Req_Arena_Exit_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 响应战斗结束
type Resp_Arena_End_ struct {
	WinUid           *int64       `protobuf:"varint,1,opt,name=WinUid" json:"WinUid,omitempty"`
	WinScore         *int32       `protobuf:"varint,2,opt,name=WinScore" json:"WinScore,omitempty"`
	WinGold          *int32       `protobuf:"varint,3,opt,name=WinGold" json:"WinGold,omitempty"`
	LostUid          *int64       `protobuf:"varint,4,opt,name=LostUid" json:"LostUid,omitempty"`
	Escape           *bool        `protobuf:"varint,5,opt,name=Escape" json:"Escape,omitempty"`
	LoseScore        *int32       `protobuf:"varint,6,opt,name=LoseScore" json:"LoseScore,omitempty"`
	LoseGold         *int32       `protobuf:"varint,7,opt,name=LoseGold" json:"LoseGold,omitempty"`
	UserID           *int64       `protobuf:"varint,8,opt,name=UserID" json:"UserID,omitempty"`
	ChestInfo        *Chest_Info_ `protobuf:"bytes,9,opt,name=ChestInfo" json:"ChestInfo,omitempty"`
	DescID           *int32       `protobuf:"varint,10,opt,name=DescID" json:"DescID,omitempty"`
	LoseStar         *int32       `protobuf:"varint,11,opt,name=LoseStar" json:"LoseStar,omitempty"`
	WinStar          *int32       `protobuf:"varint,12,opt,name=WinStar" json:"WinStar,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Resp_Arena_End_) Reset()                    { *m = Resp_Arena_End_{} }
func (m *Resp_Arena_End_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_End_) ProtoMessage()               {}
func (*Resp_Arena_End_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *Resp_Arena_End_) GetWinUid() int64 {
	if m != nil && m.WinUid != nil {
		return *m.WinUid
	}
	return 0
}

func (m *Resp_Arena_End_) GetWinScore() int32 {
	if m != nil && m.WinScore != nil {
		return *m.WinScore
	}
	return 0
}

func (m *Resp_Arena_End_) GetWinGold() int32 {
	if m != nil && m.WinGold != nil {
		return *m.WinGold
	}
	return 0
}

func (m *Resp_Arena_End_) GetLostUid() int64 {
	if m != nil && m.LostUid != nil {
		return *m.LostUid
	}
	return 0
}

func (m *Resp_Arena_End_) GetEscape() bool {
	if m != nil && m.Escape != nil {
		return *m.Escape
	}
	return false
}

func (m *Resp_Arena_End_) GetLoseScore() int32 {
	if m != nil && m.LoseScore != nil {
		return *m.LoseScore
	}
	return 0
}

func (m *Resp_Arena_End_) GetLoseGold() int32 {
	if m != nil && m.LoseGold != nil {
		return *m.LoseGold
	}
	return 0
}

func (m *Resp_Arena_End_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Arena_End_) GetChestInfo() *Chest_Info_ {
	if m != nil {
		return m.ChestInfo
	}
	return nil
}

func (m *Resp_Arena_End_) GetDescID() int32 {
	if m != nil && m.DescID != nil {
		return *m.DescID
	}
	return 0
}

func (m *Resp_Arena_End_) GetLoseStar() int32 {
	if m != nil && m.LoseStar != nil {
		return *m.LoseStar
	}
	return 0
}

func (m *Resp_Arena_End_) GetWinStar() int32 {
	if m != nil && m.WinStar != nil {
		return *m.WinStar
	}
	return 0
}

// 回复 玩家 竞技场数据更新
type Resp_PlayerUpdate_Arena_ struct {
	Score            *int32 `protobuf:"varint,1,opt,name=Score" json:"Score,omitempty"`
	Honor            *int32 `protobuf:"varint,2,opt,name=Honor" json:"Honor,omitempty"`
	DailyHonor       *int32 `protobuf:"varint,3,opt,name=DailyHonor" json:"DailyHonor,omitempty"`
	UserID           *int64 `protobuf:"varint,4,opt,name=UserID" json:"UserID,omitempty"`
	Rank             *int32 `protobuf:"varint,5,opt,name=Rank" json:"Rank,omitempty"`
	GameNum          *int32 `protobuf:"varint,6,opt,name=GameNum" json:"GameNum,omitempty"`
	GameWin          *int32 `protobuf:"varint,7,opt,name=GameWin" json:"GameWin,omitempty"`
	Star             *int32 `protobuf:"varint,8,opt,name=Star" json:"Star,omitempty"`
	Vit              *int32 `protobuf:"varint,9,opt,name=Vit" json:"Vit,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_PlayerUpdate_Arena_) Reset()                    { *m = Resp_PlayerUpdate_Arena_{} }
func (m *Resp_PlayerUpdate_Arena_) String() string            { return proto.CompactTextString(m) }
func (*Resp_PlayerUpdate_Arena_) ProtoMessage()               {}
func (*Resp_PlayerUpdate_Arena_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *Resp_PlayerUpdate_Arena_) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetHonor() int32 {
	if m != nil && m.Honor != nil {
		return *m.Honor
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetDailyHonor() int32 {
	if m != nil && m.DailyHonor != nil {
		return *m.DailyHonor
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetGameNum() int32 {
	if m != nil && m.GameNum != nil {
		return *m.GameNum
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetGameWin() int32 {
	if m != nil && m.GameWin != nil {
		return *m.GameWin
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *Resp_PlayerUpdate_Arena_) GetVit() int32 {
	if m != nil && m.Vit != nil {
		return *m.Vit
	}
	return 0
}

// 请求 竞技场断线重连
type Req_Arena_Reconn_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_Reconn_) Reset()                    { *m = Req_Arena_Reconn_{} }
func (m *Req_Arena_Reconn_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Reconn_) ProtoMessage()               {}
func (*Req_Arena_Reconn_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *Req_Arena_Reconn_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 响应 竞技场断线重连
type Resp_Arena_Reconn_ struct {
	UserID           *int64                       `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	RoomID           *int32                       `protobuf:"varint,2,opt,name=RoomID" json:"RoomID,omitempty"`
	PlayerRed        *Arena_Player_Info           `protobuf:"bytes,3,opt,name=PlayerRed" json:"PlayerRed,omitempty"`
	PlayerBlue       *Arena_Player_Info           `protobuf:"bytes,4,opt,name=PlayerBlue" json:"PlayerBlue,omitempty"`
	Ret              []int32                      `protobuf:"varint,5,rep,name=Ret" json:"Ret,omitempty"`
	Step             *int32                       `protobuf:"varint,6,opt,name=Step" json:"Step,omitempty"`
	RemainStep       *int32                       `protobuf:"varint,7,opt,name=RemainStep" json:"RemainStep,omitempty"`
	EndTime          *int64                       `protobuf:"varint,8,opt,name=EndTime" json:"EndTime,omitempty"`
	Status           *int32                       `protobuf:"varint,9,opt,name=Status" json:"Status,omitempty"`
	Heroes           []*Arena_Battle_MonsterInfo_ `protobuf:"bytes,10,rep,name=Heroes" json:"Heroes,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *Resp_Arena_Reconn_) Reset()                    { *m = Resp_Arena_Reconn_{} }
func (m *Resp_Arena_Reconn_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Arena_Reconn_) ProtoMessage()               {}
func (*Resp_Arena_Reconn_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *Resp_Arena_Reconn_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Arena_Reconn_) GetRoomID() int32 {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return 0
}

func (m *Resp_Arena_Reconn_) GetPlayerRed() *Arena_Player_Info {
	if m != nil {
		return m.PlayerRed
	}
	return nil
}

func (m *Resp_Arena_Reconn_) GetPlayerBlue() *Arena_Player_Info {
	if m != nil {
		return m.PlayerBlue
	}
	return nil
}

func (m *Resp_Arena_Reconn_) GetRet() []int32 {
	if m != nil {
		return m.Ret
	}
	return nil
}

func (m *Resp_Arena_Reconn_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Resp_Arena_Reconn_) GetRemainStep() int32 {
	if m != nil && m.RemainStep != nil {
		return *m.RemainStep
	}
	return 0
}

func (m *Resp_Arena_Reconn_) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *Resp_Arena_Reconn_) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Resp_Arena_Reconn_) GetHeroes() []*Arena_Battle_MonsterInfo_ {
	if m != nil {
		return m.Heroes
	}
	return nil
}

// 请求 竞技场断线后重新开始
type Req_Arena_Reconn_Start_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Arena_Reconn_Start_) Reset()                    { *m = Req_Arena_Reconn_Start_{} }
func (m *Req_Arena_Reconn_Start_) String() string            { return proto.CompactTextString(m) }
func (*Req_Arena_Reconn_Start_) ProtoMessage()               {}
func (*Req_Arena_Reconn_Start_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *Req_Arena_Reconn_Start_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 请求 竞技场宝箱领取
type Req_Recv_Arena_Box_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Recv_Arena_Box_) Reset()                    { *m = Req_Recv_Arena_Box_{} }
func (m *Req_Recv_Arena_Box_) String() string            { return proto.CompactTextString(m) }
func (*Req_Recv_Arena_Box_) ProtoMessage()               {}
func (*Req_Recv_Arena_Box_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

// 响应 竞技场宝箱领取
type Resp_Recv_Arena_Box_ struct {
	// optional Chest_Info_ ChestInfo = 1;// 获胜方获得的宝箱
	ChestIcon        *int32          `protobuf:"varint,1,opt,name=ChestIcon" json:"ChestIcon,omitempty"`
	ChestRewards     []*Reward_Info_ `protobuf:"bytes,2,rep,name=ChestRewards" json:"ChestRewards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Recv_Arena_Box_) Reset()                    { *m = Resp_Recv_Arena_Box_{} }
func (m *Resp_Recv_Arena_Box_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Recv_Arena_Box_) ProtoMessage()               {}
func (*Resp_Recv_Arena_Box_) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *Resp_Recv_Arena_Box_) GetChestIcon() int32 {
	if m != nil && m.ChestIcon != nil {
		return *m.ChestIcon
	}
	return 0
}

func (m *Resp_Recv_Arena_Box_) GetChestRewards() []*Reward_Info_ {
	if m != nil {
		return m.ChestRewards
	}
	return nil
}

func init() {
	proto.RegisterType((*Arena_Rank_Info_)(nil), "protocol.Arena_Rank_Info_")
	proto.RegisterType((*Arena_Monster_Info_)(nil), "protocol.Arena_Monster_Info_")
	proto.RegisterType((*Arena_Battle_MonsterInfo_)(nil), "protocol.Arena_Battle_MonsterInfo_")
	proto.RegisterType((*Arena_Player_Info)(nil), "protocol.Arena_Player_Info")
	proto.RegisterType((*Req_Arena_Rank_)(nil), "protocol.Req_Arena_Rank_")
	proto.RegisterType((*Resp_Arena_Rank_)(nil), "protocol.Resp_Arena_Rank_")
	proto.RegisterType((*Req_Arena_OpenTime_)(nil), "protocol.Req_Arena_OpenTime_")
	proto.RegisterType((*Resp_Arena_OpenTime_)(nil), "protocol.Resp_Arena_OpenTime_")
	proto.RegisterType((*Req_Arena_Info_)(nil), "protocol.Req_Arena_Info_")
	proto.RegisterType((*Resp_Arena_Info_)(nil), "protocol.Resp_Arena_Info_")
	proto.RegisterType((*Req_Honor_Shop_)(nil), "protocol.Req_Honor_Shop_")
	proto.RegisterType((*Resp_Honor_Shop_)(nil), "protocol.Resp_Honor_Shop_")
	proto.RegisterType((*Req_Honor_Buy_)(nil), "protocol.Req_Honor_Buy_")
	proto.RegisterType((*Resp_Honor_Buy_)(nil), "protocol.Resp_Honor_Buy_")
	proto.RegisterType((*Arena_Reward_)(nil), "protocol.Arena_Reward_")
	proto.RegisterType((*Req_Arena_Match_)(nil), "protocol.Req_Arena_Match_")
	proto.RegisterType((*Resp_Arena_Match_)(nil), "protocol.Resp_Arena_Match_")
	proto.RegisterType((*Req_Arena_Start_)(nil), "protocol.Req_Arena_Start_")
	proto.RegisterType((*Resp_Arena_Start_)(nil), "protocol.Resp_Arena_Start_")
	proto.RegisterType((*Req_Arena_GenMonster_)(nil), "protocol.Req_Arena_GenMonster_")
	proto.RegisterType((*Resp_Arena_GenMonster_)(nil), "protocol.Resp_Arena_GenMonster_")
	proto.RegisterType((*Fw_Arena_GenMonster_)(nil), "protocol.Fw_Arena_GenMonster_")
	proto.RegisterType((*Req_Arena_Round_)(nil), "protocol.Req_Arena_Round_")
	proto.RegisterType((*Resp_Arena_Round_)(nil), "protocol.Resp_Arena_Round_")
	proto.RegisterType((*Req_Arena_Round_End_)(nil), "protocol.Req_Arena_Round_End_")
	proto.RegisterType((*Resp_Arena_Round_End_)(nil), "protocol.Resp_Arena_Round_End_")
	proto.RegisterType((*Req_Arena_Exit_)(nil), "protocol.Req_Arena_Exit_")
	proto.RegisterType((*Resp_Arena_End_)(nil), "protocol.Resp_Arena_End_")
	proto.RegisterType((*Resp_PlayerUpdate_Arena_)(nil), "protocol.Resp_PlayerUpdate_Arena_")
	proto.RegisterType((*Req_Arena_Reconn_)(nil), "protocol.Req_Arena_Reconn_")
	proto.RegisterType((*Resp_Arena_Reconn_)(nil), "protocol.Resp_Arena_Reconn_")
	proto.RegisterType((*Req_Arena_Reconn_Start_)(nil), "protocol.Req_Arena_Reconn_Start_")
	proto.RegisterType((*Req_Recv_Arena_Box_)(nil), "protocol.Req_Recv_Arena_Box_")
	proto.RegisterType((*Resp_Recv_Arena_Box_)(nil), "protocol.Resp_Recv_Arena_Box_")
}

func init() { proto.RegisterFile("arena.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0x4b, 0x6f, 0x1c, 0x45,
	0x10, 0xd6, 0xec, 0x7b, 0x7b, 0xed, 0xd8, 0xde, 0xd8, 0xce, 0x24, 0x08, 0x29, 0x4c, 0x84, 0x12,
	0xa4, 0x60, 0x90, 0x13, 0xb8, 0x70, 0x62, 0x63, 0x27, 0x31, 0x72, 0x1c, 0x6b, 0xd7, 0x4e, 0x24,
	0x0e, 0xac, 0x3a, 0x3b, 0x1d, 0x7b, 0xe4, 0xd9, 0xe9, 0x65, 0x66, 0xfc, 0xfa, 0x05, 0x1c, 0xb8,
	0x21, 0x71, 0xe1, 0xc8, 0x85, 0x33, 0x27, 0x7e, 0x13, 0xbf, 0x80, 0x2b, 0x55, 0xd5, 0xdd, 0x33,
	0x3d, 0xb3, 0xeb, 0xb5, 0x23, 0xc4, 0xc9, 0xee, 0x9a, 0xee, 0x7a, 0x7c, 0xf5, 0xd5, 0x63, 0x59,
	0x87, 0xc7, 0x22, 0xe2, 0x1b, 0x93, 0x58, 0xa6, 0xb2, 0xdb, 0xa2, 0x3f, 0x23, 0x19, 0xde, 0x63,
	0xef, 0x78, 0x22, 0x94, 0xd4, 0xfb, 0xc9, 0x61, 0xcb, 0xdf, 0xe2, 0xad, 0x61, 0x9f, 0x47, 0x27,
	0xc3, 0x9d, 0xe8, 0xbd, 0x1c, 0x76, 0x6f, 0xb1, 0xc6, 0x61, 0x22, 0xe2, 0x9d, 0x2d, 0xd7, 0xb9,
	0xef, 0x3c, 0xaa, 0xe2, 0x19, 0xbf, 0xee, 0x49, 0xb7, 0x02, 0xe7, 0x7a, 0x77, 0x81, 0xd5, 0xf6,
	0xf8, 0x58, 0xb8, 0x55, 0x38, 0xb5, 0xbb, 0x8b, 0xac, 0x3e, 0x18, 0xc9, 0x58, 0xb8, 0x35, 0xfa,
	0xb8, 0xc4, 0x9a, 0xcf, 0xe4, 0x69, 0x94, 0xc6, 0x97, 0x6e, 0x9d, 0x04, 0x5d, 0xc6, 0x5e, 0xf1,
	0x8b, 0x67, 0xc7, 0x7c, 0x92, 0x8a, 0xd8, 0x6d, 0x90, 0x6c, 0x85, 0xb5, 0x9f, 0xcb, 0x78, 0xcc,
	0xd3, 0x40, 0x46, 0x6e, 0xf3, 0x7e, 0xf5, 0x51, 0xdd, 0xfb, 0x8e, 0xdd, 0x56, 0x8e, 0xbc, 0x92,
	0x51, 0x02, 0x37, 0xb5, 0x2f, 0xcb, 0xac, 0xf5, 0x9c, 0x8f, 0x83, 0xf0, 0x52, 0x7b, 0x43, 0x06,
	0x06, 0x27, 0x41, 0x18, 0xee, 0x9e, 0x81, 0x3b, 0xf0, 0x12, 0xaf, 0x1c, 0xf0, 0x50, 0x44, 0x29,
	0x48, 0xaa, 0xa4, 0x4b, 0xb2, 0xbb, 0x4a, 0x57, 0x8f, 0xa7, 0x69, 0x28, 0x8c, 0x4a, 0xa5, 0x91,
	0xb1, 0x4a, 0xa6, 0x0b, 0xfe, 0x27, 0x35, 0xfa, 0xff, 0x97, 0x13, 0x8a, 0xa9, 0xde, 0xed, 0xb0,
	0xea, 0xbe, 0x4c, 0xf2, 0x88, 0x8c, 0xc1, 0xfa, 0x94, 0xc1, 0x06, 0x19, 0xfc, 0xb5, 0xc2, 0x56,
	0x94, 0xc5, 0xfd, 0x90, 0x5f, 0x6a, 0xe7, 0x51, 0xcb, 0x61, 0xe0, 0x6b, 0x10, 0x0d, 0x68, 0x95,
	0x22, 0x68, 0x99, 0xbd, 0xad, 0xe0, 0x4c, 0xdb, 0xf3, 0x58, 0xad, 0x2f, 0x43, 0x41, 0xf0, 0x75,
	0x36, 0x57, 0x37, 0x4c, 0xe2, 0x36, 0x50, 0xaa, 0x61, 0xf9, 0xd2, 0x06, 0x10, 0x7d, 0xe8, 0x6c,
	0x7e, 0x9c, 0x5f, 0x9c, 0x05, 0xa4, 0x95, 0x97, 0x26, 0x99, 0x81, 0xac, 0x0e, 0xd2, 0x58, 0xf0,
	0x13, 0xb7, 0x65, 0xce, 0x3b, 0x23, 0x19, 0x01, 0x36, 0x6d, 0x13, 0x36, 0x9e, 0x0f, 0xe3, 0xd0,
	0x65, 0xe4, 0x33, 0x44, 0xf0, 0x42, 0x86, 0xbe, 0xdb, 0x99, 0x91, 0xd6, 0x05, 0xf3, 0xa4, 0x2f,
	0x8e, 0x0e, 0x02, 0x08, 0x73, 0x11, 0x83, 0xf6, 0x0e, 0xd9, 0x52, 0x5f, 0xfc, 0x38, 0xb4, 0x18,
	0x36, 0x45, 0x2e, 0xa0, 0x42, 0x4f, 0x1c, 0x05, 0x11, 0x7e, 0xcd, 0xf9, 0x75, 0x70, 0x39, 0x31,
	0xd8, 0x20, 0x57, 0xe2, 0x40, 0x44, 0xfe, 0xce, 0x16, 0x66, 0xa4, 0x0a, 0x6a, 0xbf, 0x67, 0xcb,
	0x7d, 0x91, 0x4c, 0xe6, 0xea, 0x7d, 0x04, 0x28, 0x2a, 0x95, 0x08, 0xce, 0xbd, 0x32, 0x38, 0x16,
	0xdd, 0x0b, 0xe6, 0xbc, 0x35, 0x76, 0x3b, 0x77, 0xf9, 0xf5, 0x44, 0x44, 0x18, 0xce, 0xd0, 0xfb,
	0x86, 0xad, 0x5a, 0x26, 0x33, 0x39, 0x72, 0xc1, 0x1c, 0xf2, 0x80, 0x9e, 0x85, 0x32, 0x11, 0x24,
	0xaa, 0x10, 0x0c, 0x9f, 0xd8, 0x30, 0xcc, 0xac, 0x31, 0xef, 0xef, 0x6a, 0x21, 0x26, 0x75, 0x09,
	0x30, 0xa6, 0xa3, 0xa2, 0x4a, 0x46, 0xff, 0xed, 0xc8, 0xcf, 0x95, 0x77, 0x3f, 0x67, 0x0b, 0x74,
	0xa9, 0x2f, 0xce, 0x79, 0xec, 0x27, 0x54, 0x02, 0x9d, 0xcd, 0x3b, 0x53, 0x01, 0xd3, 0x67, 0xdb,
	0x70, 0x8d, 0x9e, 0x43, 0x00, 0x03, 0xc1, 0x13, 0x4a, 0x7c, 0xdd, 0xc0, 0x4f, 0xc8, 0x35, 0x8c,
	0xbd, 0x17, 0xc0, 0xdb, 0xbd, 0xd3, 0xb1, 0xe6, 0x8d, 0x16, 0xbc, 0x0d, 0x22, 0x4d, 0x1c, 0x0c,
	0xf8, 0x58, 0x24, 0x29, 0xb2, 0x45, 0x73, 0xe7, 0x31, 0x5b, 0x20, 0x91, 0xf1, 0x89, 0x91, 0x4f,
	0xeb, 0x16, 0x95, 0x95, 0x37, 0x2a, 0xcc, 0x87, 0x48, 0x1b, 0x75, 0xb1, 0x33, 0xf7, 0xa2, 0x0d,
	0xf6, 0xc2, 0x34, 0xd8, 0xc4, 0x39, 0x2c, 0xad, 0x97, 0x32, 0x92, 0xb1, 0x7b, 0xcb, 0xf0, 0x74,
	0x8b, 0x43, 0xff, 0x50, 0xb2, 0x25, 0x92, 0xad, 0xb1, 0xc5, 0x5c, 0x06, 0x2c, 0x76, 0x97, 0x49,
	0x7c, 0x87, 0x2d, 0xed, 0x89, 0x0b, 0x70, 0xfa, 0x7d, 0x2c, 0x92, 0x63, 0x52, 0xb9, 0x42, 0x2a,
	0x21, 0xe4, 0x9e, 0xbc, 0xa0, 0xf8, 0xba, 0x06, 0x03, 0x78, 0x36, 0x48, 0x79, 0xec, 0xde, 0x36,
	0x98, 0xd1, 0x69, 0x95, 0x4e, 0xe8, 0x67, 0xe8, 0xab, 0xac, 0xad, 0x99, 0x02, 0x7f, 0x13, 0xa4,
	0xee, 0x3a, 0x51, 0xec, 0xa9, 0xa2, 0x03, 0x59, 0x1f, 0x0e, 0x8e, 0xe5, 0x64, 0x66, 0x55, 0xec,
	0xf2, 0x24, 0x55, 0x2a, 0xa8, 0x2a, 0xbc, 0xdf, 0x1d, 0xcd, 0x90, 0x79, 0xef, 0x3e, 0x65, 0xf5,
	0x9d, 0x54, 0x8c, 0x13, 0x4d, 0xfb, 0xab, 0x80, 0x04, 0x8c, 0xf6, 0xe3, 0x60, 0x24, 0x54, 0xbf,
	0x44, 0x7f, 0x7b, 0xa7, 0x97, 0x18, 0xb0, 0xaa, 0xb0, 0x3a, 0x5e, 0xd8, 0x0d, 0xc6, 0xe0, 0xb1,
	0xea, 0x78, 0xd8, 0x1b, 0x40, 0x2d, 0x98, 0xa1, 0x7e, 0x37, 0x0b, 0xa9, 0x26, 0xd1, 0xb8, 0xc7,
	0x6e, 0xe5, 0xa1, 0x81, 0xce, 0xa1, 0xf5, 0xd4, 0x31, 0xd8, 0xe0, 0x99, 0x2a, 0xae, 0x62, 0x1a,
	0x4f, 0x0f, 0x26, 0x12, 0xdc, 0x50, 0x15, 0x78, 0x82, 0xf0, 0x64, 0x71, 0x92, 0x12, 0x8b, 0x21,
	0xce, 0x75, 0x0c, 0xc9, 0x22, 0xc9, 0xb4, 0x6b, 0xfb, 0xaa, 0x9d, 0x64, 0xf4, 0xa0, 0x66, 0xeb,
	0xfd, 0xec, 0xb0, 0xc5, 0x62, 0x81, 0x64, 0xad, 0x39, 0xab, 0x37, 0x68, 0xcd, 0x59, 0xeb, 0xd6,
	0x82, 0x11, 0x91, 0x41, 0x0d, 0x40, 0xcb, 0xb9, 0xda, 0x5c, 0xe7, 0x70, 0x90, 0x88, 0xa3, 0x31,
	0x0c, 0x0e, 0x5d, 0x69, 0x28, 0x00, 0xd6, 0x60, 0x6d, 0x51, 0xb1, 0x79, 0x23, 0x4c, 0xb1, 0x69,
	0x14, 0xaf, 0x78, 0x3a, 0x3a, 0x26, 0x00, 0x5f, 0x4f, 0x08, 0x2e, 0xc7, 0x04, 0xa4, 0x53, 0xae,
	0xea, 0xff, 0x0b, 0xc6, 0xd4, 0xd0, 0x41, 0x23, 0xe4, 0x52, 0x67, 0xf3, 0xa3, 0x72, 0xf5, 0x5b,
	0x63, 0xc9, 0xfb, 0xcb, 0x61, 0x2b, 0x56, 0xab, 0xc9, 0xcd, 0xf4, 0xa5, 0x2c, 0xe4, 0xa9, 0x0f,
	0xf3, 0xc2, 0x47, 0xe7, 0x54, 0xe0, 0x1b, 0xac, 0xad, 0xd4, 0xf4, 0x85, 0x7f, 0x03, 0x3b, 0xb9,
	0x63, 0xbd, 0xf0, 0xd4, 0x27, 0xb8, 0xaf, 0x79, 0x00, 0x70, 0xbc, 0x14, 0xb1, 0xc4, 0x3e, 0x9f,
	0xd1, 0x4e, 0x87, 0xda, 0x20, 0x76, 0x79, 0x36, 0x3c, 0x88, 0x5c, 0x3a, 0xdd, 0x48, 0x4f, 0x0a,
	0xc1, 0xe9, 0x4b, 0x54, 0x9e, 0x62, 0x72, 0x55, 0x0b, 0x7d, 0xc8, 0xda, 0x07, 0xfc, 0x5d, 0x28,
	0x2c, 0x04, 0xad, 0xb1, 0x9b, 0x7d, 0x9a, 0x6a, 0x9e, 0xde, 0x98, 0xad, 0xe5, 0x0e, 0xbd, 0x10,
	0x91, 0x19, 0xb9, 0x53, 0x75, 0x69, 0x1c, 0x50, 0x48, 0x7e, 0xcd, 0xda, 0x14, 0x28, 0xe8, 0x34,
	0xfd, 0xfa, 0x41, 0x19, 0x98, 0x19, 0xab, 0x8b, 0x17, 0xb1, 0x75, 0x2b, 0xb6, 0xff, 0xdf, 0xde,
	0x3b, 0xb6, 0xfa, 0xfc, 0xfc, 0x83, 0xad, 0x3d, 0x9e, 0xb6, 0x76, 0x37, 0xb7, 0xa6, 0xec, 0x98,
	0x0b, 0x43, 0xef, 0x17, 0xc7, 0x4e, 0x2a, 0x51, 0x6e, 0x58, 0x4c, 0x88, 0x33, 0x27, 0x21, 0x85,
	0xc8, 0x2a, 0x37, 0x8e, 0xcc, 0x8a, 0xa0, 0x6a, 0x86, 0xc6, 0xbe, 0x3c, 0x17, 0xa6, 0x2b, 0xfc,
	0x59, 0x2c, 0x11, 0xed, 0x15, 0x3c, 0x7a, 0x13, 0x8c, 0x52, 0xe8, 0x1d, 0x2a, 0xec, 0xa7, 0x8a,
	0xaf, 0x58, 0x0e, 0x1f, 0x60, 0xfa, 0x2b, 0xd6, 0xc2, 0x57, 0x54, 0x14, 0x37, 0xcf, 0x05, 0xed,
	0x56, 0x3c, 0xf2, 0x07, 0xc2, 0xd7, 0x83, 0x3b, 0x0f, 0xa1, 0x4e, 0x5c, 0x7c, 0x82, 0x1b, 0x4a,
	0x11, 0xc7, 0x6d, 0xf4, 0x1a, 0x46, 0x4f, 0x5f, 0xa4, 0xb3, 0x9b, 0x87, 0xf7, 0x03, 0x12, 0xb8,
	0x14, 0x27, 0xbd, 0xba, 0xa6, 0x62, 0xca, 0xf8, 0xad, 0x43, 0xdf, 0xc7, 0xc7, 0x0a, 0x1f, 0xdc,
	0x7a, 0x6b, 0xd3, 0x9b, 0xcf, 0xf6, 0x45, 0x30, 0xa3, 0x60, 0xff, 0x71, 0x74, 0xbf, 0xd7, 0x97,
	0x34, 0xd2, 0xb0, 0x5f, 0xe4, 0xcb, 0x33, 0x34, 0x23, 0x38, 0x5b, 0xd3, 0x10, 0x3d, 0x02, 0x09,
	0xed, 0xa3, 0x55, 0x23, 0xd8, 0x95, 0x49, 0x9a, 0x99, 0x46, 0x1d, 0xdb, 0xc9, 0x88, 0x4f, 0xd4,
	0x22, 0xdd, 0xa2, 0x91, 0x0a, 0x9b, 0x82, 0x52, 0xd2, 0x30, 0x3d, 0x0e, 0x45, 0xa4, 0xa5, 0x59,
	0xc2, 0xa7, 0xa5, 0xb7, 0x48, 0xbd, 0xdb, 0x20, 0x11, 0xdb, 0x44, 0xc4, 0xb5, 0x3c, 0x5b, 0xf4,
	0x29, 0x5f, 0xe8, 0xb6, 0x44, 0x32, 0x82, 0x97, 0xcc, 0xd6, 0x4d, 0x5b, 0x41, 0xc7, 0x72, 0x99,
	0x04, 0xb4, 0x2e, 0x7b, 0x7f, 0x38, 0xcc, 0xa5, 0xc8, 0x55, 0x13, 0x3c, 0x9c, 0xf8, 0x3c, 0x15,
	0x1a, 0x86, 0xf2, 0x18, 0xca, 0xc6, 0x56, 0x65, 0xc6, 0x56, 0x53, 0x2d, 0xf9, 0x5e, 0x33, 0x55,
	0x49, 0x7b, 0x5c, 0xbd, 0xbc, 0xc7, 0x35, 0xca, 0x7b, 0x5c, 0xb3, 0xb0, 0xc3, 0xb4, 0xec, 0x8d,
	0x85, 0xf6, 0x39, 0xef, 0x01, 0x96, 0x43, 0xc6, 0x2d, 0x01, 0xb3, 0x2f, 0x9a, 0x4e, 0xe4, 0x6f,
	0x15, 0xd6, 0xb5, 0xc9, 0x34, 0xfb, 0x9a, 0x35, 0x68, 0xfe, 0xfb, 0x58, 0x11, 0x37, 0x19, 0x2b,
	0xba, 0x00, 0xd4, 0x48, 0x31, 0xbc, 0x6e, 0x18, 0x18, 0xfb, 0x62, 0xcc, 0x31, 0x2b, 0x20, 0x6b,
	0x96, 0xb9, 0xde, 0x32, 0x0e, 0x03, 0x2e, 0xe9, 0x69, 0xa2, 0x97, 0xdb, 0x27, 0xac, 0x81, 0x05,
	0x2c, 0xcc, 0x5a, 0x7b, 0xa3, 0x56, 0xfa, 0x19, 0xbb, 0x33, 0x85, 0xe0, 0x15, 0x13, 0x4c, 0xff,
	0x02, 0x81, 0x4b, 0x67, 0xfa, 0x3e, 0x2c, 0x9f, 0x43, 0xef, 0xad, 0xfe, 0x05, 0x52, 0x92, 0x17,
	0xd7, 0x6f, 0x67, 0xe6, 0xfa, 0x3d, 0x77, 0x19, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x80, 0x91,
	0x2c, 0x15, 0x27, 0x10, 0x00, 0x00,
}
