// Code generated by protoc-gen-go.
// source: boss.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Boss_Info_ struct {
	ID               *int32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Hp               *int64  `protobuf:"varint,2,opt,name=Hp" json:"Hp,omitempty"`
	Damage           *int32  `protobuf:"varint,3,opt,name=Damage" json:"Damage,omitempty"`
	PhyAtk           *int32  `protobuf:"varint,4,opt,name=PhyAtk" json:"PhyAtk,omitempty"`
	MagAtk           *int32  `protobuf:"varint,5,opt,name=MagAtk" json:"MagAtk,omitempty"`
	PhyDef           *int32  `protobuf:"varint,6,opt,name=PhyDef" json:"PhyDef,omitempty"`
	MagDef           *int32  `protobuf:"varint,7,opt,name=MagDef" json:"MagDef,omitempty"`
	AtkRang          *int32  `protobuf:"varint,8,opt,name=AtkRang" json:"AtkRang,omitempty"`
	AtkFeq           *int32  `protobuf:"varint,9,opt,name=AtkFeq" json:"AtkFeq,omitempty"`
	Speed            *int32  `protobuf:"varint,10,opt,name=Speed" json:"Speed,omitempty"`
	CurHp            *int64  `protobuf:"varint,11,opt,name=CurHp" json:"CurHp,omitempty"`
	Lv               *int32  `protobuf:"varint,12,opt,name=Lv" json:"Lv,omitempty"`
	DescIDs          []int32 `protobuf:"varint,13,rep,name=DescIDs" json:"DescIDs,omitempty"`
	SkillID          []int32 `protobuf:"varint,14,rep,name=SkillID" json:"SkillID,omitempty"`
	SkillLv          []int32 `protobuf:"varint,15,rep,name=SkillLv" json:"SkillLv,omitempty"`
	CritAtk          *int32  `protobuf:"varint,16,opt,name=CritAtk" json:"CritAtk,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Boss_Info_) Reset()                    { *m = Boss_Info_{} }
func (m *Boss_Info_) String() string            { return proto.CompactTextString(m) }
func (*Boss_Info_) ProtoMessage()               {}
func (*Boss_Info_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Boss_Info_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Boss_Info_) GetHp() int64 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Boss_Info_) GetDamage() int32 {
	if m != nil && m.Damage != nil {
		return *m.Damage
	}
	return 0
}

func (m *Boss_Info_) GetPhyAtk() int32 {
	if m != nil && m.PhyAtk != nil {
		return *m.PhyAtk
	}
	return 0
}

func (m *Boss_Info_) GetMagAtk() int32 {
	if m != nil && m.MagAtk != nil {
		return *m.MagAtk
	}
	return 0
}

func (m *Boss_Info_) GetPhyDef() int32 {
	if m != nil && m.PhyDef != nil {
		return *m.PhyDef
	}
	return 0
}

func (m *Boss_Info_) GetMagDef() int32 {
	if m != nil && m.MagDef != nil {
		return *m.MagDef
	}
	return 0
}

func (m *Boss_Info_) GetAtkRang() int32 {
	if m != nil && m.AtkRang != nil {
		return *m.AtkRang
	}
	return 0
}

func (m *Boss_Info_) GetAtkFeq() int32 {
	if m != nil && m.AtkFeq != nil {
		return *m.AtkFeq
	}
	return 0
}

func (m *Boss_Info_) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Boss_Info_) GetCurHp() int64 {
	if m != nil && m.CurHp != nil {
		return *m.CurHp
	}
	return 0
}

func (m *Boss_Info_) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *Boss_Info_) GetDescIDs() []int32 {
	if m != nil {
		return m.DescIDs
	}
	return nil
}

func (m *Boss_Info_) GetSkillID() []int32 {
	if m != nil {
		return m.SkillID
	}
	return nil
}

func (m *Boss_Info_) GetSkillLv() []int32 {
	if m != nil {
		return m.SkillLv
	}
	return nil
}

func (m *Boss_Info_) GetCritAtk() int32 {
	if m != nil && m.CritAtk != nil {
		return *m.CritAtk
	}
	return 0
}

// 玩家的boss相关信息
type PlayerBoss_Info_ struct {
	MyRank           *int32 `protobuf:"varint,1,opt,name=MyRank" json:"MyRank,omitempty"`
	Damage           *int64 `protobuf:"varint,2,opt,name=Damage" json:"Damage,omitempty"`
	HitTimes         *int32 `protobuf:"varint,3,opt,name=HitTimes" json:"HitTimes,omitempty"`
	ShareTimes       *int32 `protobuf:"varint,4,opt,name=ShareTimes" json:"ShareTimes,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerBoss_Info_) Reset()                    { *m = PlayerBoss_Info_{} }
func (m *PlayerBoss_Info_) String() string            { return proto.CompactTextString(m) }
func (*PlayerBoss_Info_) ProtoMessage()               {}
func (*PlayerBoss_Info_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *PlayerBoss_Info_) GetMyRank() int32 {
	if m != nil && m.MyRank != nil {
		return *m.MyRank
	}
	return 0
}

func (m *PlayerBoss_Info_) GetDamage() int64 {
	if m != nil && m.Damage != nil {
		return *m.Damage
	}
	return 0
}

func (m *PlayerBoss_Info_) GetHitTimes() int32 {
	if m != nil && m.HitTimes != nil {
		return *m.HitTimes
	}
	return 0
}

func (m *PlayerBoss_Info_) GetShareTimes() int32 {
	if m != nil && m.ShareTimes != nil {
		return *m.ShareTimes
	}
	return 0
}

// 请求 boss信息
type Req_Boss_Info_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	UserLv           *int32 `protobuf:"varint,2,opt,name=UserLv" json:"UserLv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Boss_Info_) Reset()                    { *m = Req_Boss_Info_{} }
func (m *Req_Boss_Info_) String() string            { return proto.CompactTextString(m) }
func (*Req_Boss_Info_) ProtoMessage()               {}
func (*Req_Boss_Info_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *Req_Boss_Info_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Boss_Info_) GetUserLv() int32 {
	if m != nil && m.UserLv != nil {
		return *m.UserLv
	}
	return 0
}

// 响应 boss信息
type Resp_Boss_Info_ struct {
	UserID           *int64            `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	OpenTime         *int64            `protobuf:"varint,2,opt,name=OpenTime" json:"OpenTime,omitempty"`
	EndTime          *int64            `protobuf:"varint,3,opt,name=EndTime" json:"EndTime,omitempty"`
	Bosses           *Boss_Info_       `protobuf:"bytes,4,opt,name=Bosses" json:"Bosses,omitempty"`
	DamageInfo       []*Damage_Info_   `protobuf:"bytes,5,rep,name=DamageInfo" json:"DamageInfo,omitempty"`
	TableInfo        *TableInfo_       `protobuf:"bytes,6,opt,name=TableInfo" json:"TableInfo,omitempty"`
	Step             *int32            `protobuf:"varint,7,opt,name=Step" json:"Step,omitempty"`
	PlayerInfo       *PlayerBoss_Info_ `protobuf:"bytes,8,opt,name=PlayerInfo" json:"PlayerInfo,omitempty"`
	SceneID          *int32            `protobuf:"varint,9,opt,name=SceneID" json:"SceneID,omitempty"`
	CanHit           *bool             `protobuf:"varint,10,opt,name=CanHit" json:"CanHit,omitempty"`
	AddTimesPrice    *int32            `protobuf:"varint,11,opt,name=AddTimesPrice" json:"AddTimesPrice,omitempty"`
	HitBossDuration  *int64            `protobuf:"varint,12,opt,name=HitBossDuration" json:"HitBossDuration,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Resp_Boss_Info_) Reset()                    { *m = Resp_Boss_Info_{} }
func (m *Resp_Boss_Info_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Boss_Info_) ProtoMessage()               {}
func (*Resp_Boss_Info_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *Resp_Boss_Info_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Boss_Info_) GetOpenTime() int64 {
	if m != nil && m.OpenTime != nil {
		return *m.OpenTime
	}
	return 0
}

func (m *Resp_Boss_Info_) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *Resp_Boss_Info_) GetBosses() *Boss_Info_ {
	if m != nil {
		return m.Bosses
	}
	return nil
}

func (m *Resp_Boss_Info_) GetDamageInfo() []*Damage_Info_ {
	if m != nil {
		return m.DamageInfo
	}
	return nil
}

func (m *Resp_Boss_Info_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *Resp_Boss_Info_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Resp_Boss_Info_) GetPlayerInfo() *PlayerBoss_Info_ {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Resp_Boss_Info_) GetSceneID() int32 {
	if m != nil && m.SceneID != nil {
		return *m.SceneID
	}
	return 0
}

func (m *Resp_Boss_Info_) GetCanHit() bool {
	if m != nil && m.CanHit != nil {
		return *m.CanHit
	}
	return false
}

func (m *Resp_Boss_Info_) GetAddTimesPrice() int32 {
	if m != nil && m.AddTimesPrice != nil {
		return *m.AddTimesPrice
	}
	return 0
}

func (m *Resp_Boss_Info_) GetHitBossDuration() int64 {
	if m != nil && m.HitBossDuration != nil {
		return *m.HitBossDuration
	}
	return 0
}

// 请求 攻击boss
type Req_Hit_Boss_ struct {
	UserID           *int64        `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	Damage           *Damage_Info_ `protobuf:"bytes,2,opt,name=Damage" json:"Damage,omitempty"`
	UserLv           *int32        `protobuf:"varint,3,opt,name=UserLv" json:"UserLv,omitempty"`
	TableInfo        *TableInfo_   `protobuf:"bytes,4,opt,name=TableInfo" json:"TableInfo,omitempty"`
	HitDuration      *int64        `protobuf:"varint,5,opt,name=HitDuration" json:"HitDuration,omitempty"`
	Step             *int32        `protobuf:"varint,6,opt,name=Step" json:"Step,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Req_Hit_Boss_) Reset()                    { *m = Req_Hit_Boss_{} }
func (m *Req_Hit_Boss_) String() string            { return proto.CompactTextString(m) }
func (*Req_Hit_Boss_) ProtoMessage()               {}
func (*Req_Hit_Boss_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *Req_Hit_Boss_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Hit_Boss_) GetDamage() *Damage_Info_ {
	if m != nil {
		return m.Damage
	}
	return nil
}

func (m *Req_Hit_Boss_) GetUserLv() int32 {
	if m != nil && m.UserLv != nil {
		return *m.UserLv
	}
	return 0
}

func (m *Req_Hit_Boss_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *Req_Hit_Boss_) GetHitDuration() int64 {
	if m != nil && m.HitDuration != nil {
		return *m.HitDuration
	}
	return 0
}

func (m *Req_Hit_Boss_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

// 响应 攻击boss
type Resp_Hit_Boss_ struct {
	UserID           *int64            `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	CurDamage        *int64            `protobuf:"varint,2,opt,name=CurDamage" json:"CurDamage,omitempty"`
	Rewards          []*Reward_Info_   `protobuf:"bytes,3,rep,name=Rewards" json:"Rewards,omitempty"`
	PlayerInfo       *PlayerBoss_Info_ `protobuf:"bytes,4,opt,name=PlayerInfo" json:"PlayerInfo,omitempty"`
	BossCurHp        *int64            `protobuf:"varint,5,opt,name=BossCurHp" json:"BossCurHp,omitempty"`
	SpeRewards       []*Reward_Info_   `protobuf:"bytes,6,rep,name=SpeRewards" json:"SpeRewards,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Resp_Hit_Boss_) Reset()                    { *m = Resp_Hit_Boss_{} }
func (m *Resp_Hit_Boss_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Hit_Boss_) ProtoMessage()               {}
func (*Resp_Hit_Boss_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *Resp_Hit_Boss_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Hit_Boss_) GetCurDamage() int64 {
	if m != nil && m.CurDamage != nil {
		return *m.CurDamage
	}
	return 0
}

func (m *Resp_Hit_Boss_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Resp_Hit_Boss_) GetPlayerInfo() *PlayerBoss_Info_ {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Resp_Hit_Boss_) GetBossCurHp() int64 {
	if m != nil && m.BossCurHp != nil {
		return *m.BossCurHp
	}
	return 0
}

func (m *Resp_Hit_Boss_) GetSpeRewards() []*Reward_Info_ {
	if m != nil {
		return m.SpeRewards
	}
	return nil
}

// 请求 获取世界boss排名
type Req_Get_BossRank_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	UserLv           *int32 `protobuf:"varint,2,opt,name=UserLv" json:"UserLv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Get_BossRank_) Reset()                    { *m = Req_Get_BossRank_{} }
func (m *Req_Get_BossRank_) String() string            { return proto.CompactTextString(m) }
func (*Req_Get_BossRank_) ProtoMessage()               {}
func (*Req_Get_BossRank_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *Req_Get_BossRank_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Get_BossRank_) GetUserLv() int32 {
	if m != nil && m.UserLv != nil {
		return *m.UserLv
	}
	return 0
}

// 响应 获取世界boss排名
type Resp_Get_BossRank_ struct {
	UserID           *int64          `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	RankNo           []int32         `protobuf:"varint,2,rep,name=RankNo" json:"RankNo,omitempty"`
	DamageInfo       []*Damage_Info_ `protobuf:"bytes,3,rep,name=DamageInfo" json:"DamageInfo,omitempty"`
	RefreshTime      *int64          `protobuf:"varint,4,opt,name=RefreshTime" json:"RefreshTime,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Get_BossRank_) Reset()                    { *m = Resp_Get_BossRank_{} }
func (m *Resp_Get_BossRank_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Get_BossRank_) ProtoMessage()               {}
func (*Resp_Get_BossRank_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *Resp_Get_BossRank_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Get_BossRank_) GetRankNo() []int32 {
	if m != nil {
		return m.RankNo
	}
	return nil
}

func (m *Resp_Get_BossRank_) GetDamageInfo() []*Damage_Info_ {
	if m != nil {
		return m.DamageInfo
	}
	return nil
}

func (m *Resp_Get_BossRank_) GetRefreshTime() int64 {
	if m != nil && m.RefreshTime != nil {
		return *m.RefreshTime
	}
	return 0
}

// 请求 增加攻击次数
type Req_Add_HitTimes_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	UserLv           *int32 `protobuf:"varint,2,opt,name=UserLv" json:"UserLv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Add_HitTimes_) Reset()                    { *m = Req_Add_HitTimes_{} }
func (m *Req_Add_HitTimes_) String() string            { return proto.CompactTextString(m) }
func (*Req_Add_HitTimes_) ProtoMessage()               {}
func (*Req_Add_HitTimes_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *Req_Add_HitTimes_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Add_HitTimes_) GetUserLv() int32 {
	if m != nil && m.UserLv != nil {
		return *m.UserLv
	}
	return 0
}

// 响应 增加攻击次数
type Resp_Add_HitTimes_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	HitTimes         *int32 `protobuf:"varint,2,opt,name=HitTimes" json:"HitTimes,omitempty"`
	AddTimesPrice    *int32 `protobuf:"varint,3,opt,name=AddTimesPrice" json:"AddTimesPrice,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Add_HitTimes_) Reset()                    { *m = Resp_Add_HitTimes_{} }
func (m *Resp_Add_HitTimes_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Add_HitTimes_) ProtoMessage()               {}
func (*Resp_Add_HitTimes_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *Resp_Add_HitTimes_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Add_HitTimes_) GetHitTimes() int32 {
	if m != nil && m.HitTimes != nil {
		return *m.HitTimes
	}
	return 0
}

func (m *Resp_Add_HitTimes_) GetAddTimesPrice() int32 {
	if m != nil && m.AddTimesPrice != nil {
		return *m.AddTimesPrice
	}
	return 0
}

// 请求 奖励信息
type Req_Boss_RewardInfo_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	UserLv           *int32 `protobuf:"varint,2,opt,name=UserLv" json:"UserLv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Boss_RewardInfo_) Reset()                    { *m = Req_Boss_RewardInfo_{} }
func (m *Req_Boss_RewardInfo_) String() string            { return proto.CompactTextString(m) }
func (*Req_Boss_RewardInfo_) ProtoMessage()               {}
func (*Req_Boss_RewardInfo_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *Req_Boss_RewardInfo_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Boss_RewardInfo_) GetUserLv() int32 {
	if m != nil && m.UserLv != nil {
		return *m.UserLv
	}
	return 0
}

// 响应 奖励信息
type Resp_Boss_RewardInfo_ struct {
	UserID           *int64              `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	RankRewards      []*Rank_RewardInfo_ `protobuf:"bytes,3,rep,name=RankRewards" json:"RankRewards,omitempty"`
	HpPer            []int32             `protobuf:"varint,4,rep,name=HpPer" json:"HpPer,omitempty"`
	SpeRewards       []*Reward_Info_     `protobuf:"bytes,5,rep,name=SpeRewards" json:"SpeRewards,omitempty"`
	UserName         []string            `protobuf:"bytes,6,rep,name=UserName" json:"UserName,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Resp_Boss_RewardInfo_) Reset()                    { *m = Resp_Boss_RewardInfo_{} }
func (m *Resp_Boss_RewardInfo_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Boss_RewardInfo_) ProtoMessage()               {}
func (*Resp_Boss_RewardInfo_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *Resp_Boss_RewardInfo_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Boss_RewardInfo_) GetRankRewards() []*Rank_RewardInfo_ {
	if m != nil {
		return m.RankRewards
	}
	return nil
}

func (m *Resp_Boss_RewardInfo_) GetHpPer() []int32 {
	if m != nil {
		return m.HpPer
	}
	return nil
}

func (m *Resp_Boss_RewardInfo_) GetSpeRewards() []*Reward_Info_ {
	if m != nil {
		return m.SpeRewards
	}
	return nil
}

func (m *Resp_Boss_RewardInfo_) GetUserName() []string {
	if m != nil {
		return m.UserName
	}
	return nil
}

// 排行榜奖励
type Rank_RewardInfo_ struct {
	RankRange        *int32          `protobuf:"varint,1,opt,name=RankRange" json:"RankRange,omitempty"`
	Rewards          []*Reward_Info_ `protobuf:"bytes,2,rep,name=Rewards" json:"Rewards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Rank_RewardInfo_) Reset()                    { *m = Rank_RewardInfo_{} }
func (m *Rank_RewardInfo_) String() string            { return proto.CompactTextString(m) }
func (*Rank_RewardInfo_) ProtoMessage()               {}
func (*Rank_RewardInfo_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *Rank_RewardInfo_) GetRankRange() int32 {
	if m != nil && m.RankRange != nil {
		return *m.RankRange
	}
	return 0
}

func (m *Rank_RewardInfo_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

// 响应  更新boss信息
type Resp_BossInfo_Update_ struct {
	UserID           *int64          `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	DamageInfo       []*Damage_Info_ `protobuf:"bytes,2,rep,name=DamageInfo" json:"DamageInfo,omitempty"`
	CurHp            *int64          `protobuf:"varint,3,opt,name=CurHp" json:"CurHp,omitempty"`
	BossLv           *int32          `protobuf:"varint,4,opt,name=BossLv" json:"BossLv,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_BossInfo_Update_) Reset()                    { *m = Resp_BossInfo_Update_{} }
func (m *Resp_BossInfo_Update_) String() string            { return proto.CompactTextString(m) }
func (*Resp_BossInfo_Update_) ProtoMessage()               {}
func (*Resp_BossInfo_Update_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *Resp_BossInfo_Update_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_BossInfo_Update_) GetDamageInfo() []*Damage_Info_ {
	if m != nil {
		return m.DamageInfo
	}
	return nil
}

func (m *Resp_BossInfo_Update_) GetCurHp() int64 {
	if m != nil && m.CurHp != nil {
		return *m.CurHp
	}
	return 0
}

func (m *Resp_BossInfo_Update_) GetBossLv() int32 {
	if m != nil && m.BossLv != nil {
		return *m.BossLv
	}
	return 0
}

// 响应 boss玩家信息更新
type Resp_Boss_PlayerInfo_ struct {
	UserID           *int64            `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	PlayerInfo       *PlayerBoss_Info_ `protobuf:"bytes,2,opt,name=PlayerInfo" json:"PlayerInfo,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Resp_Boss_PlayerInfo_) Reset()                    { *m = Resp_Boss_PlayerInfo_{} }
func (m *Resp_Boss_PlayerInfo_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Boss_PlayerInfo_) ProtoMessage()               {}
func (*Resp_Boss_PlayerInfo_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *Resp_Boss_PlayerInfo_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Boss_PlayerInfo_) GetPlayerInfo() *PlayerBoss_Info_ {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

// 请求 沙盘消除结束，开始打boss
type Req_Boss_Battle_Begin_ struct {
	UserID           *int64 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	UserLv           *int32 `protobuf:"varint,2,opt,name=UserLv" json:"UserLv,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Boss_Battle_Begin_) Reset()                    { *m = Req_Boss_Battle_Begin_{} }
func (m *Req_Boss_Battle_Begin_) String() string            { return proto.CompactTextString(m) }
func (*Req_Boss_Battle_Begin_) ProtoMessage()               {}
func (*Req_Boss_Battle_Begin_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *Req_Boss_Battle_Begin_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Boss_Battle_Begin_) GetUserLv() int32 {
	if m != nil && m.UserLv != nil {
		return *m.UserLv
	}
	return 0
}

// 响应 通知客户端攻击boss超时，该结束了
type Resp_Notice_Boss_Battle_TimeOut_ struct {
	UserIDs          []int64 `protobuf:"varint,1,rep,name=UserIDs" json:"UserIDs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Notice_Boss_Battle_TimeOut_) Reset()         { *m = Resp_Notice_Boss_Battle_TimeOut_{} }
func (m *Resp_Notice_Boss_Battle_TimeOut_) String() string { return proto.CompactTextString(m) }
func (*Resp_Notice_Boss_Battle_TimeOut_) ProtoMessage()    {}
func (*Resp_Notice_Boss_Battle_TimeOut_) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{16}
}

func (m *Resp_Notice_Boss_Battle_TimeOut_) GetUserIDs() []int64 {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

// 伤害列表
type Damage_Info_ struct {
	Damage           *int64  `protobuf:"varint,1,opt,name=Damage" json:"Damage,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	HeroID           *int32  `protobuf:"varint,3,opt,name=HeroID" json:"HeroID,omitempty"`
	Lv               *int32  `protobuf:"varint,4,opt,name=Lv" json:"Lv,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Damage_Info_) Reset()                    { *m = Damage_Info_{} }
func (m *Damage_Info_) String() string            { return proto.CompactTextString(m) }
func (*Damage_Info_) ProtoMessage()               {}
func (*Damage_Info_) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *Damage_Info_) GetDamage() int64 {
	if m != nil && m.Damage != nil {
		return *m.Damage
	}
	return 0
}

func (m *Damage_Info_) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Damage_Info_) GetHeroID() int32 {
	if m != nil && m.HeroID != nil {
		return *m.HeroID
	}
	return 0
}

func (m *Damage_Info_) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func init() {
	proto.RegisterType((*Boss_Info_)(nil), "protocol.Boss_Info_")
	proto.RegisterType((*PlayerBoss_Info_)(nil), "protocol.PlayerBoss_Info_")
	proto.RegisterType((*Req_Boss_Info_)(nil), "protocol.Req_Boss_Info_")
	proto.RegisterType((*Resp_Boss_Info_)(nil), "protocol.Resp_Boss_Info_")
	proto.RegisterType((*Req_Hit_Boss_)(nil), "protocol.Req_Hit_Boss_")
	proto.RegisterType((*Resp_Hit_Boss_)(nil), "protocol.Resp_Hit_Boss_")
	proto.RegisterType((*Req_Get_BossRank_)(nil), "protocol.Req_Get_BossRank_")
	proto.RegisterType((*Resp_Get_BossRank_)(nil), "protocol.Resp_Get_BossRank_")
	proto.RegisterType((*Req_Add_HitTimes_)(nil), "protocol.Req_Add_HitTimes_")
	proto.RegisterType((*Resp_Add_HitTimes_)(nil), "protocol.Resp_Add_HitTimes_")
	proto.RegisterType((*Req_Boss_RewardInfo_)(nil), "protocol.Req_Boss_RewardInfo_")
	proto.RegisterType((*Resp_Boss_RewardInfo_)(nil), "protocol.Resp_Boss_RewardInfo_")
	proto.RegisterType((*Rank_RewardInfo_)(nil), "protocol.Rank_RewardInfo_")
	proto.RegisterType((*Resp_BossInfo_Update_)(nil), "protocol.Resp_BossInfo_Update_")
	proto.RegisterType((*Resp_Boss_PlayerInfo_)(nil), "protocol.Resp_Boss_PlayerInfo_")
	proto.RegisterType((*Req_Boss_Battle_Begin_)(nil), "protocol.Req_Boss_Battle_Begin_")
	proto.RegisterType((*Resp_Notice_Boss_Battle_TimeOut_)(nil), "protocol.Resp_Notice_Boss_Battle_TimeOut_")
	proto.RegisterType((*Damage_Info_)(nil), "protocol.Damage_Info_")
}

func init() { proto.RegisterFile("boss.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 789 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x56, 0x51, 0x4f, 0x1a, 0x41,
	0x10, 0x0e, 0x77, 0x80, 0x30, 0x8a, 0x20, 0x55, 0x7b, 0xf1, 0xc9, 0x5c, 0x9a, 0xda, 0xf4, 0x81,
	0x36, 0x35, 0x69, 0xfa, 0xaa, 0xd2, 0x16, 0x93, 0x8a, 0x04, 0x34, 0xed, 0x1b, 0x59, 0x61, 0xc4,
	0x8b, 0x78, 0x77, 0xde, 0x1d, 0x6d, 0x7c, 0xee, 0x4f, 0x69, 0xfa, 0x6b, 0x9a, 0xf4, 0x37, 0x75,
	0x76, 0x76, 0x17, 0xee, 0x24, 0x1e, 0x7d, 0x92, 0xd9, 0xdd, 0x99, 0xf9, 0xe6, 0x9b, 0x6f, 0xe6,
	0x04, 0xb8, 0x0a, 0xe2, 0xb8, 0x15, 0x46, 0x41, 0x12, 0x34, 0x2b, 0xfc, 0x67, 0x14, 0x4c, 0xf7,
	0xe0, 0x4a, 0xc4, 0xa8, 0x4e, 0xdd, 0x9f, 0x16, 0xc0, 0x31, 0x3d, 0x1a, 0x9e, 0xfa, 0xd7, 0xc1,
	0xb0, 0x09, 0x60, 0x9d, 0xb6, 0x9d, 0xc2, 0x7e, 0xe1, 0x55, 0x49, 0xfe, 0xee, 0x84, 0x8e, 0x45,
	0xbf, 0xed, 0xe6, 0x26, 0x94, 0xdb, 0xe2, 0x4e, 0x4c, 0xd0, 0xb1, 0xf9, 0x8e, 0xec, 0xde, 0xcd,
	0xc3, 0x51, 0x72, 0xeb, 0x14, 0x8d, 0x7d, 0x26, 0x26, 0xd2, 0x2e, 0xa5, 0xee, 0xdb, 0x78, 0xed,
	0x94, 0x53, 0xf7, 0xd2, 0x5e, 0x63, 0xbb, 0x0e, 0x6b, 0xf4, 0xb8, 0x2f, 0xfc, 0x89, 0x53, 0x31,
	0x0f, 0xe8, 0xe0, 0x13, 0xde, 0x3b, 0x55, 0xb6, 0x6b, 0x50, 0x1a, 0x84, 0x88, 0x63, 0x07, 0x8c,
	0x79, 0x32, 0x8b, 0x08, 0xce, 0x3a, 0xc3, 0x21, 0x68, 0x5f, 0xbe, 0x3b, 0x1b, 0x26, 0x54, 0x1b,
	0xe3, 0xd1, 0x69, 0x3b, 0x76, 0x6a, 0xfb, 0xb6, 0x3a, 0x18, 0xdc, 0x7a, 0xd3, 0x29, 0x15, 0xb2,
	0x99, 0x39, 0x20, 0x97, 0xba, 0x39, 0x38, 0x89, 0xbc, 0x44, 0xc2, 0x6d, 0xc8, 0x18, 0xee, 0x37,
	0x68, 0xf4, 0xa6, 0xe2, 0x01, 0xa3, 0x14, 0x15, 0x12, 0xf2, 0x03, 0x21, 0xbc, 0xd5, 0x74, 0x2c,
	0x28, 0x50, 0x94, 0x34, 0xa0, 0xd2, 0xf1, 0x92, 0x0b, 0xef, 0x0e, 0x63, 0x4d, 0x0a, 0xc1, 0x1a,
	0xdc, 0x88, 0x08, 0xd5, 0x19, 0x13, 0xe3, 0xbe, 0x85, 0xcd, 0x3e, 0xde, 0x0f, 0xb3, 0x71, 0x2f,
	0x63, 0x8c, 0x34, 0xcd, 0xb6, 0xb1, 0x09, 0x9c, 0xc5, 0x1e, 0x7f, 0x2d, 0xa8, 0xf7, 0x31, 0x0e,
	0xf3, 0x7c, 0x28, 0xf7, 0x79, 0x88, 0xbe, 0x4c, 0xa4, 0xd1, 0x50, 0x49, 0x1f, 0xfd, 0x31, 0x1f,
	0xd8, 0x7c, 0xf0, 0x02, 0xca, 0x32, 0x80, 0x06, 0xb2, 0xfe, 0x6e, 0xbb, 0x65, 0xfa, 0xdf, 0x4a,
	0x05, 0x7e, 0x0d, 0xa0, 0x8a, 0x92, 0x26, 0xf5, 0xce, 0xa6, 0x97, 0xbb, 0x8b, 0x97, 0xea, 0x4e,
	0xbf, 0x3d, 0x80, 0xea, 0x85, 0xb8, 0x9a, 0xaa, 0xa7, 0xe5, 0xc7, 0x41, 0xe7, 0x57, 0xc3, 0xe6,
	0x06, 0x14, 0x07, 0x09, 0x86, 0xba, 0xd5, 0x2d, 0x00, 0xc5, 0x2d, 0xfb, 0x55, 0xd8, 0x6f, 0x6f,
	0xe1, 0xb7, 0xc4, 0xbb, 0xec, 0xd6, 0x08, 0x7d, 0xa4, 0x62, 0xab, 0x86, 0xf8, 0x13, 0xe1, 0x13,
	0xd7, 0xac, 0x85, 0x4a, 0x73, 0x07, 0x6a, 0x47, 0x63, 0x2e, 0x35, 0xee, 0x45, 0xde, 0x08, 0x59,
	0x13, 0xa5, 0xe6, 0x73, 0xa8, 0xd3, 0x1b, 0x19, 0xa8, 0x3d, 0x8b, 0x44, 0xe2, 0x05, 0x3e, 0x0b,
	0xc4, 0x76, 0x7f, 0x15, 0xa0, 0x26, 0x7b, 0x40, 0xb7, 0x8a, 0xd3, 0x25, 0x3a, 0x5f, 0x66, 0x5a,
	0xfb, 0x34, 0x03, 0x8b, 0x56, 0xa9, 0x86, 0x67, 0x18, 0x29, 0xe6, 0x30, 0xf2, 0x0c, 0xd6, 0x29,
	0xfb, 0x1c, 0x57, 0x89, 0xb3, 0x1a, 0x9a, 0x78, 0x42, 0xdc, 0x3f, 0x05, 0xa9, 0x14, 0x6a, 0xfb,
	0xd3, 0x30, 0xb7, 0xa0, 0x4a, 0x43, 0x90, 0x11, 0xe1, 0x01, 0xac, 0xf5, 0xf1, 0x87, 0x88, 0xc6,
	0x52, 0x83, 0x8f, 0x9a, 0xa7, 0x2e, 0x34, 0xf4, 0x6c, 0x17, 0x8a, 0x2b, 0xbb, 0x40, 0xb9, 0xa4,
	0xa5, 0x86, 0x4e, 0xe1, 0x25, 0xad, 0xd0, 0x48, 0x9a, 0x74, 0xe5, 0xbc, 0x74, 0xee, 0x21, 0x6c,
	0x49, 0xca, 0x3f, 0xa3, 0xaa, 0x45, 0x8e, 0xd1, 0x6a, 0xe5, 0xcf, 0xa0, 0xc9, 0x0c, 0xac, 0xf4,
	0x92, 0x17, 0xdd, 0x80, 0xbc, 0xe4, 0x30, 0x67, 0x25, 0x6c, 0xe7, 0x4a, 0x98, 0xfa, 0xd0, 0xc7,
	0xeb, 0x08, 0xe3, 0x1b, 0x9e, 0x94, 0x22, 0xeb, 0x43, 0x63, 0x25, 0x4d, 0x0d, 0xcd, 0x40, 0xaf,
	0xc6, 0x7a, 0xa6, 0xb1, 0xe6, 0x7b, 0xa5, 0x77, 0x04, 0xfb, 0x2d, 0x8b, 0x97, 0x95, 0xe4, 0xbe,
	0x87, 0xed, 0xf9, 0x9a, 0x50, 0x44, 0xfe, 0xdf, 0xb2, 0xf8, 0x5d, 0x80, 0x9d, 0xc5, 0xb2, 0xc8,
	0xf3, 0x7c, 0x43, 0xa5, 0x13, 0x6d, 0x59, 0xb5, 0xa4, 0x14, 0xc0, 0x64, 0xa7, 0x03, 0xd0, 0xca,
	0xed, 0x84, 0x3d, 0x8c, 0x88, 0x25, 0x4d, 0x73, 0xaa, 0xfb, 0xa5, 0x5c, 0xb1, 0x51, 0xd9, 0x32,
	0x77, 0x57, 0x10, 0xc7, 0x52, 0x27, 0x55, 0xb7, 0x0b, 0x8d, 0xa5, 0x04, 0x24, 0x31, 0x46, 0x44,
	0x1f, 0x01, 0xd4, 0x3b, 0x36, 0x25, 0x67, 0x2b, 0x57, 0x5f, 0x51, 0xaa, 0x6c, 0x3e, 0xb9, 0x0c,
	0xc7, 0x22, 0xc1, 0xe5, 0xb2, 0xb3, 0xea, 0xb0, 0x72, 0xd5, 0x31, 0xff, 0xc8, 0xd8, 0x86, 0x6b,
	0x19, 0x9e, 0xb8, 0x56, 0xab, 0xfc, 0x6b, 0x9a, 0xea, 0xc5, 0x30, 0x2d, 0xe7, 0xcc, 0xce, 0x9a,
	0xb5, 0x6a, 0xd6, 0xdc, 0x0f, 0xb0, 0x3b, 0x6f, 0xfe, 0xb1, 0x48, 0x92, 0x29, 0x0e, 0x8f, 0x71,
	0xe2, 0xf9, 0xab, 0xdb, 0x7f, 0x08, 0xfb, 0x0c, 0xa9, 0x1b, 0x24, 0xa4, 0xa5, 0x4c, 0x04, 0x29,
	0xb1, 0xf3, 0x59, 0xc2, 0xfb, 0x54, 0xc5, 0x88, 0x29, 0x88, 0x4d, 0x7a, 0xef, 0xc0, 0xc6, 0xe3,
	0xad, 0xa6, 0x77, 0x4a, 0xc1, 0xec, 0x25, 0xee, 0x9c, 0x4c, 0x51, 0x95, 0xb7, 0x1d, 0x8c, 0x02,
	0x82, 0x60, 0x9b, 0xff, 0x0a, 0x0c, 0x23, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xcf, 0x24,
	0x4f, 0x5f, 0x08, 0x00, 0x00,
}
