// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 请求 创建新用户
type Req_Create_User_ struct {
	Account          *string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Create_User_) Reset()                    { *m = Req_Create_User_{} }
func (m *Req_Create_User_) String() string            { return proto.CompactTextString(m) }
func (*Req_Create_User_) ProtoMessage()               {}
func (*Req_Create_User_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *Req_Create_User_) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

// 响应 创建新用户
type Resp_Create_User_ struct {
	Account          *string `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
	UserID           *int64  `protobuf:"varint,3,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Create_User_) Reset()                    { *m = Resp_Create_User_{} }
func (m *Resp_Create_User_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Create_User_) ProtoMessage()               {}
func (*Resp_Create_User_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *Resp_Create_User_) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Resp_Create_User_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 请求 更新邮件列表
type Req_Mail_Update_ struct {
	UserID           *int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	MailID           []int64 `protobuf:"varint,2,rep,name=MailID" json:"MailID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Mail_Update_) Reset()                    { *m = Req_Mail_Update_{} }
func (m *Req_Mail_Update_) String() string            { return proto.CompactTextString(m) }
func (*Req_Mail_Update_) ProtoMessage()               {}
func (*Req_Mail_Update_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *Req_Mail_Update_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Mail_Update_) GetMailID() []int64 {
	if m != nil {
		return m.MailID
	}
	return nil
}

// 响应 更新邮件列表
type Resp_Mail_Update_ struct {
	UserID           *int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	MailID           []int64 `protobuf:"varint,2,rep,name=MailID" json:"MailID,omitempty"`
	Status           []int32 `protobuf:"varint,3,rep,name=Status" json:"Status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Mail_Update_) Reset()                    { *m = Resp_Mail_Update_{} }
func (m *Resp_Mail_Update_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Mail_Update_) ProtoMessage()               {}
func (*Resp_Mail_Update_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *Resp_Mail_Update_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Mail_Update_) GetMailID() []int64 {
	if m != nil {
		return m.MailID
	}
	return nil
}

func (m *Resp_Mail_Update_) GetStatus() []int32 {
	if m != nil {
		return m.Status
	}
	return nil
}

// 新邮件推送
type Resp_NewMail_Push_ struct {
	MailID           *int64  `protobuf:"varint,1,opt,name=MailID" json:"MailID,omitempty"`
	UserIDs          []int64 `protobuf:"varint,2,rep,name=UserIDs" json:"UserIDs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_NewMail_Push_) Reset()                    { *m = Resp_NewMail_Push_{} }
func (m *Resp_NewMail_Push_) String() string            { return proto.CompactTextString(m) }
func (*Resp_NewMail_Push_) ProtoMessage()               {}
func (*Resp_NewMail_Push_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

func (m *Resp_NewMail_Push_) GetMailID() int64 {
	if m != nil && m.MailID != nil {
		return *m.MailID
	}
	return 0
}

func (m *Resp_NewMail_Push_) GetUserIDs() []int64 {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

// 测试协议
type Resp_Test_Func_ struct {
	Type             *int32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	UserID           *int64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	Exp              *int32 `protobuf:"varint,3,opt,name=Exp" json:"Exp,omitempty"`
	Fid              *int32 `protobuf:"varint,4,opt,name=Fid" json:"Fid,omitempty"`
	Prob             *int32 `protobuf:"varint,5,opt,name=Prob" json:"Prob,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Test_Func_) Reset()                    { *m = Resp_Test_Func_{} }
func (m *Resp_Test_Func_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Test_Func_) ProtoMessage()               {}
func (*Resp_Test_Func_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

func (m *Resp_Test_Func_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Resp_Test_Func_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Test_Func_) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Resp_Test_Func_) GetFid() int32 {
	if m != nil && m.Fid != nil {
		return *m.Fid
	}
	return 0
}

func (m *Resp_Test_Func_) GetProb() int32 {
	if m != nil && m.Prob != nil {
		return *m.Prob
	}
	return 0
}

// 快速通关
type Resp_LazyPass_ struct {
	Uid              *int64  `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Cid              []int32 `protobuf:"varint,2,rep,name=Cid" json:"Cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_LazyPass_) Reset()                    { *m = Resp_LazyPass_{} }
func (m *Resp_LazyPass_) String() string            { return proto.CompactTextString(m) }
func (*Resp_LazyPass_) ProtoMessage()               {}
func (*Resp_LazyPass_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *Resp_LazyPass_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Resp_LazyPass_) GetCid() []int32 {
	if m != nil {
		return m.Cid
	}
	return nil
}

// 通知服务器玩家上线
type Req_Notice_User_Online_ struct {
	Uid              *int64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Notice_User_Online_) Reset()                    { *m = Req_Notice_User_Online_{} }
func (m *Req_Notice_User_Online_) String() string            { return proto.CompactTextString(m) }
func (*Req_Notice_User_Online_) ProtoMessage()               {}
func (*Req_Notice_User_Online_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{7} }

func (m *Req_Notice_User_Online_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type Resp_Notice_User_Online_ struct {
	ShopId           []int32 `protobuf:"varint,1,rep,name=ShopId" json:"ShopId,omitempty"`
	UserID           *int64  `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Notice_User_Online_) Reset()                    { *m = Resp_Notice_User_Online_{} }
func (m *Resp_Notice_User_Online_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Notice_User_Online_) ProtoMessage()               {}
func (*Resp_Notice_User_Online_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{8} }

func (m *Resp_Notice_User_Online_) GetShopId() []int32 {
	if m != nil {
		return m.ShopId
	}
	return nil
}

func (m *Resp_Notice_User_Online_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*Req_Create_User_)(nil), "protocol.Req_Create_User_")
	proto.RegisterType((*Resp_Create_User_)(nil), "protocol.Resp_Create_User_")
	proto.RegisterType((*Req_Mail_Update_)(nil), "protocol.Req_Mail_Update_")
	proto.RegisterType((*Resp_Mail_Update_)(nil), "protocol.Resp_Mail_Update_")
	proto.RegisterType((*Resp_NewMail_Push_)(nil), "protocol.Resp_NewMail_Push_")
	proto.RegisterType((*Resp_Test_Func_)(nil), "protocol.Resp_Test_Func_")
	proto.RegisterType((*Resp_LazyPass_)(nil), "protocol.Resp_LazyPass_")
	proto.RegisterType((*Req_Notice_User_Online_)(nil), "protocol.Req_Notice_User_Online_")
	proto.RegisterType((*Resp_Notice_User_Online_)(nil), "protocol.Resp_Notice_User_Online_")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0x49, 0xb6, 0xf9, 0x3e, 0x1d, 0x4b, 0xab, 0xb9, 0x98, 0x63, 0x59, 0x41, 0x8a, 0x07,
	0x0f, 0xa2, 0x17, 0x6f, 0x12, 0x2d, 0x14, 0xb4, 0x86, 0xda, 0xe0, 0x71, 0x89, 0xe9, 0x42, 0x03,
	0x21, 0xbb, 0x66, 0x37, 0x6a, 0xfd, 0xeb, 0xdd, 0x99, 0x44, 0x88, 0xa8, 0x07, 0x4f, 0xcb, 0x63,
	0xdf, 0xfb, 0xcd, 0x9b, 0x81, 0xa1, 0x91, 0xf5, 0x8b, 0xac, 0x4f, 0x75, 0xad, 0xac, 0x0a, 0x77,
	0xe8, 0xc9, 0x55, 0xc9, 0x8f, 0x60, 0x7f, 0x29, 0x9f, 0x45, 0x5c, 0xcb, 0xcc, 0x4a, 0x91, 0x3a,
	0x97, 0x08, 0xc7, 0xf0, 0xff, 0x2a, 0xcf, 0x55, 0x53, 0xd9, 0xc8, 0x9b, 0x78, 0xd3, 0x5d, 0x7e,
	0x0e, 0x07, 0x4b, 0x69, 0xf4, 0xaf, 0x2e, 0x1f, 0x5d, 0xe1, 0x08, 0xfe, 0xe1, 0xcf, 0xfc, 0x3a,
	0x62, 0x4e, 0x33, 0x7e, 0xd6, 0xa2, 0xef, 0xb2, 0xa2, 0x14, 0xa9, 0x5e, 0x63, 0xb2, 0xe7, 0x41,
	0x32, 0x43, 0x8d, 0xff, 0x4e, 0xfb, 0x13, 0xe6, 0x32, 0x71, 0x37, 0xe9, 0x2f, 0x21, 0xd4, 0x0f,
	0x36, 0xb3, 0x8d, 0x71, 0x83, 0xd9, 0x34, 0xe0, 0x17, 0x10, 0x12, 0x64, 0x21, 0x5f, 0x89, 0x93,
	0x34, 0x66, 0x23, 0x7a, 0xa9, 0x96, 0xe2, 0xfa, 0xb7, 0x54, 0xd3, 0xcd, 0x7e, 0x84, 0x31, 0xc5,
	0x56, 0xd2, 0x58, 0x31, 0x6b, 0xaa, 0x5c, 0x84, 0x43, 0x18, 0xac, 0xb6, 0x5a, 0x52, 0x22, 0xe8,
	0xf5, 0xf0, 0x89, 0xb0, 0x07, 0xec, 0xe6, 0x4d, 0xd3, 0xb6, 0x01, 0x8a, 0x59, 0xb1, 0x8e, 0x06,
	0x24, 0x5c, 0x2e, 0xa9, 0xd5, 0x53, 0x14, 0xa0, 0xe2, 0x27, 0x30, 0x22, 0xf0, 0x6d, 0xf6, 0xbe,
	0x4d, 0x32, 0x63, 0x04, 0x9a, 0x53, 0x67, 0xf6, 0x3e, 0x31, 0xb1, 0x13, 0x3e, 0x75, 0x3f, 0x86,
	0x43, 0x3c, 0xda, 0x42, 0xd9, 0x22, 0xef, 0x2e, 0x7d, 0x5f, 0x95, 0x45, 0x25, 0xbf, 0x86, 0xf8,
	0x25, 0x44, 0xed, 0x8e, 0x3f, 0x18, 0xf1, 0x1e, 0x1b, 0xa5, 0xe7, 0xe8, 0x65, 0xdf, 0x7b, 0x7f,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x06, 0xca, 0x02, 0x0c, 0x02, 0x00, 0x00,
}
